export type Rank = 'Zivilist' | 'Genosse' | 'Mitglied' | 'Offizier' | 'Funktionär' | 'Direktor' | 'Vizeminister' | 'Minister' | 'Vizeführer' | 'OBERSTER FÜHRER';
export type Loyalty = 'Bestätigt' | 'In Prüfung' | 'Beobachtet';
export type Clearance = 'ÖFFENTLICH' | 'INTERN' | 'VERTRAULICH' | 'GEHEIM' | 'STRENG GEHEIM';

export interface Comment {
  author: string;
  authorRank: Rank;
  text: string;
  hint?: string;
}

export interface Post {
  id: string;
  authorId: string;
  timestamp: string;
  text: string;
  imageCaption?: string;
  imageColor?: string;
  likes: number;
  retweets?: number;
  replies?: number;
  comments: Comment[];
  location?: string;
  hint?: string;
  pinned?: boolean;
  locked?: boolean;
  requiredRank?: Rank;
  clearance?: Clearance;
  bookmarked?: boolean;
  clueId?: string;
}

export interface Profile {
  id: string;
  name: string;
  handle: string;
  rank: Rank;
  rankLevel: number;
  position: string;
  influence: 'Gering' | 'Mittel' | 'Hoch' | 'Sehr Hoch' | 'Höchste Stufe';
  loyalty: Loyalty;
  followers: number;
  following: number;
  bio: string;
  publicParole: string;
  privateHint: string;
  joinedYear: number;
  accentColor: string;
  initials: string;
  status: 'Aktiv' | 'Abwesend' | 'Gesperrt' | 'Verborgen';
  location: string;
  sector: string;
  avatarUrl?: string;
}

export const rankOrder: Rank[] = [
  'Zivilist', 'Genosse', 'Mitglied', 'Offizier', 'Funktionär',
  'Direktor', 'Vizeminister', 'Minister', 'Vizeführer', 'OBERSTER FÜHRER',
];

export const profiles: Profile[] = [
  {
    id: 'fuehrer',
    name: 'Erster Kanzler Volker Brandt',
    handle: '@kanzler.brandt',
    rank: 'OBERSTER FÜHRER',
    rankLevel: 10,
    position: 'Erster Kanzler der Allianz',
    influence: 'Höchste Stufe',
    loyalty: 'Bestätigt',
    followers: 47,
    following: 0,
    bio: 'Diener der Allianz. Verkörperung des Willens.',
    publicParole: 'Die Zukunft gehört den Disziplinierten.',
    privateHint: 'Seine 47 Follower sind handverlesen — keine Schwäche, sondern ein Statement. Niemand außerhalb des Konsiliums liest seine Worte.',
    joinedYear: 2022,
    accentColor: '#f4212e',
    initials: 'VB',
    status: 'Verborgen',
    location: 'Zentrale, Sektor A0',
    sector: 'A0',
  },
  {
    id: 'vizefuehrer',
    name: 'Stellvertreterin Dr. Kira Halstenbeck',
    handle: '@vizef.halstenbeck',
    rank: 'Vizeführer',
    rankLevel: 9,
    position: 'Stellvertretende Erste Kanzlerin',
    influence: 'Höchste Stufe',
    loyalty: 'Bestätigt',
    followers: 1823,
    following: 11,
    bio: 'Architektin der Ordnung. Loyal. Unbeugsam.',
    publicParole: 'Stärke ist die einzige Sprache, die alle verstehen.',
    privateHint: 'Empfängt wöchentlich die PROMETHEUS-Lage. Sie hat als Erste unterschrieben, als die Observationen 0027 Bürger umfassten.',
    joinedYear: 2021,
    accentColor: '#ff4d5c',
    initials: 'KH',
    status: 'Aktiv',
    location: 'Zentrale, Sektor A0',
    sector: 'A0',
  },
  {
    id: 'seidt',
    name: 'Dr. Daniel Seidt',
    handle: '@d.seidt',
    rank: 'Minister',
    rankLevel: 9,
    position: 'Staatssekretär · Sicherheitsdirektorat (SD)',
    influence: 'Sehr Hoch',
    loyalty: 'In Prüfung',
    followers: 312,
    following: 89,
    bio: 'Staatssekretär. Familienvater. Ausdauersportler.',
    publicParole: 'Innere Sicherheit ist die Grundlage jeder Freiheit.',
    privateHint: 'Aktenzeichen „ARGOS" taucht mehrfach in seinen Notizen auf. Letzter Login: vor drei Tagen. Sein Dienstgerät gilt als verloren.',
    joinedYear: 2020,
    accentColor: '#1d9bf0',
    initials: 'DS',
    status: 'Abwesend',
    location: 'Sektor A7 / Bergstation Privatresidenz',
    sector: 'A7',
  },
  {
    id: 'bellmer',
    name: 'Friedrich-Wilhelm Bellmer',
    handle: '@bm.bellmer',
    rank: 'Minister',
    rankLevel: 9,
    position: 'Direktor · Sicherheitsdirektorat (SD)',
    influence: 'Sehr Hoch',
    loyalty: 'Bestätigt',
    followers: 1057,
    following: 34,
    bio: 'Streng. Loyal. Pflichtbewusst.',
    publicParole: 'Ordnung ist das höchste Gut der Republik.',
    privateHint: 'Hat im Juli 2025 veranlasst, dass die Anfrage zur HYDRA-Vergabe „in Richtung Digitalisierung" umformuliert wird.',
    joinedYear: 2018,
    accentColor: '#1e3a5f',
    initials: 'FB',
    status: 'Aktiv',
    location: 'Sektor A0',
    sector: 'A0',
  },
  {
    id: 'klingspor',
    name: 'Dr. Helmut Klingspor',
    handle: '@ehrenv.klingspor',
    rank: 'OBERSTER FÜHRER',
    rankLevel: 10,
    position: 'Ehrenkanzler, Patriarch des Konsiliums',
    influence: 'Höchste Stufe',
    loyalty: 'Bestätigt',
    followers: 2204,
    following: 3,
    bio: 'Über 40 Jahre im Dienst der Allianz. Noch immer wachsam.',
    publicParole: 'Die Mühen der Ebene sind die wahren Taten.',
    privateHint: 'Hat einen Anruf von Seidt am 14. April entgegengenommen — und die angeforderte Liste nie geschickt.',
    joinedYear: 2009,
    accentColor: '#2d3748',
    initials: 'HK',
    status: 'Aktiv',
    location: 'Sektor B12',
    sector: 'B12',
  },
  {
    id: 'reitmair',
    name: 'Dr. Christoph Reitmair',
    handle: '@bmvg.reitmair',
    rank: 'Minister',
    rankLevel: 9,
    position: 'Direktor · Wehrdirektorat (WD)',
    influence: 'Sehr Hoch',
    loyalty: 'Bestätigt',
    followers: 891,
    following: 22,
    bio: 'Staatstragend. Verlässlich. Pflichtschuldig.',
    publicParole: 'Stärke durch Sicherheit.',
    privateHint: 'Die HYDRA-Vergabestelle sitzt direkt in seinem Direktorat — Aktenzeichen seit Q1/26 in Umlauf.',
    joinedYear: 2019,
    accentColor: '#10b981',
    initials: 'CR',
    status: 'Aktiv',
    location: 'Sektor A0',
    sector: 'A0',
  },
  {
    id: 'vehlow',
    name: 'Britta Vehlow',
    handle: '@b.vehlow',
    rank: 'Direktor',
    rankLevel: 8,
    position: 'Vize-Direktorin · Zentralamt für Informationssicherheit (ZFI)',
    influence: 'Sehr Hoch',
    loyalty: 'Bestätigt',
    followers: 142,
    following: 56,
    bio: 'Staatliche Verantwortung in zweiter Reihe.',
    publicParole: 'Stille ist eine Tugend.',
    privateHint: 'Verfasserin der Klartext-Direktive zur PROMETHEUS-Endabstimmung vom 2. April 2026.',
    joinedYear: 2017,
    accentColor: '#475569',
    initials: 'BV',
    status: 'Aktiv',
    location: 'Sektor C3',
    sector: 'C3',
  },
  {
    id: 'lugner',
    name: 'Sara Lugner',
    handle: '@s.lugner',
    rank: 'Direktor',
    rankLevel: 8,
    position: 'Residentur-Leiterin · Auslands-Nachrichtendienst (AND)',
    influence: 'Hoch',
    loyalty: 'Bestätigt',
    followers: 67,
    following: 28,
    bio: 'Dienst an der Allianz.',
    publicParole: 'Wissen ist Verantwortung.',
    privateHint: 'Bindeglied für Datenflüsse aus dem Auslandsbereich — die technische Seite der PROMETHEUS-Operation.',
    joinedYear: 2016,
    accentColor: '#0d9488',
    initials: 'SL',
    status: 'Abwesend',
    location: 'Sektor A0 · AND-Residentur',
    sector: 'A0',
  },
  {
    id: 'prack',
    name: 'Leonie Prack',
    handle: '@l.prack',
    rank: 'Direktor',
    rankLevel: 8,
    position: 'Ministerialdirektorin · Wirtschaftsdirektorat (WIDI)',
    influence: 'Hoch',
    loyalty: 'Bestätigt',
    followers: 234,
    following: 41,
    bio: 'Wirtschaftspolitik mit Haltung.',
    publicParole: 'Wachstum durch Verlässlichkeit.',
    privateHint: 'Hat im WIDI-Vergabeverfahren die Wertungs-Matrix zugunsten von WARECOM angepasst — handschriftlicher Vermerk existiert.',
    joinedYear: 2018,
    accentColor: '#a855f7',
    initials: 'LP',
    status: 'Aktiv',
    location: 'Sektor A0',
    sector: 'A0',
  },
  {
    id: 'kaltenborn',
    name: 'Tobias Kaltenborn',
    handle: '@t.kaltenborn',
    rank: 'Vizeminister',
    rankLevel: 7,
    position: 'Parlamentarischer Sprecher · Innere Sicherheit',
    influence: 'Hoch',
    loyalty: 'Bestätigt',
    followers: 512,
    following: 187,
    bio: 'Parlamentarier. Pragmatiker.',
    publicParole: 'Sicherheit ist nicht verhandelbar.',
    privateHint: 'Hat im März 2026 eine parlamentarische Anfrage zur HYDRA-Vergabe abgeschwächt — Chiffre „FELD".',
    joinedYear: 2014,
    accentColor: '#06b6d4',
    initials: 'TK',
    status: 'Aktiv',
    location: 'Sektor A0 / Sektor D4',
    sector: 'A0',
  },
  {
    id: 'siemons',
    name: 'Tobias Siemons',
    handle: '@t.siemons',
    rank: 'Vizeminister',
    rankLevel: 7,
    position: 'Bundesschatzmeister · INITIATIVE 2030',
    influence: 'Hoch',
    loyalty: 'Bestätigt',
    followers: 88,
    following: 14,
    bio: 'Zahlen. Verlässlichkeit. Pflicht.',
    publicParole: 'Verwaltung ist Staatskunst.',
    privateHint: 'Geschäftsführer von „INITIATIVE 2030" — Quartalsweise „Pakete" an die Bergstation.',
    joinedYear: 2015,
    accentColor: '#ec4899',
    initials: 'TS',
    status: 'Aktiv',
    location: 'Sektor E5 / A0',
    sector: 'E5',
  },
  {
    id: 'beilschmidt',
    name: 'Tom Beilschmidt',
    handle: '@t.beilschmidt',
    rank: 'Funktionär',
    rankLevel: 6,
    position: 'Referatsleiter III-2 · ZFI',
    influence: 'Mittel',
    loyalty: 'Bestätigt',
    followers: 41,
    following: 102,
    bio: 'Still. Verlässlich. Unsichtbar — wo es nötig ist.',
    publicParole: 'Dienst ist Dienst.',
    privateHint: 'Hat das Konzeptpapier „PROMETHEUS-Operation: Zielpersonen & Methoden" am 28. Februar 2026 verfasst.',
    joinedYear: 2013,
    accentColor: '#1e293b',
    initials: 'TB',
    status: 'Aktiv',
    location: 'Sektor C3',
    sector: 'C3',
  },
  {
    id: 'foht',
    name: 'Dr. Beatrice Foht',
    handle: '@b.foht',
    rank: 'Vizeminister',
    rankLevel: 7,
    position: 'Amtschefin · Sicherheitsdirektorat (SD)',
    influence: 'Hoch',
    loyalty: 'In Prüfung',
    followers: 156,
    following: 19,
    bio: 'Verwaltung. Kontrolle. Gewissen.',
    publicParole: 'Verlässlichkeit im Verfahren.',
    privateHint: 'Hat im April 2026 die interne Revision zur HYDRA-Vergabe angefordert — ihre Beschwerde wurde von Vehlow zurückgewiesen.',
    joinedYear: 2012,
    accentColor: '#64748b',
    initials: 'BF',
    status: 'Aktiv',
    location: 'Sektor A0',
    sector: 'A0',
  },
  {
    id: 'kahlen',
    name: 'Dr. Konrad Kahlen',
    handle: '@k.kahlen',
    rank: 'Funktionär',
    rankLevel: 6,
    position: 'Vorstand · WARECOM Industries AG',
    influence: 'Mittel',
    loyalty: 'Bestätigt',
    followers: 73,
    following: 38,
    bio: 'Industrie. Innovation. Patriotischer Auftrag.',
    publicParole: 'Sicherheit ist die Voraussetzung für Wohlstand.',
    privateHint: 'Hauptempfänger der HYDRA-Vergabe — Mailwechsel zur „Aktualisierung der Wertungs-Matrix, Punkt 4.3" auf Seidts Dienstgerät.',
    joinedYear: 2022,
    accentColor: '#4f46e5',
    initials: 'KK',
    status: 'Aktiv',
    location: 'Sektor F2',
    sector: 'F2',
  },
  {
    id: 'haller',
    name: 'Viktor Haller',
    handle: '@v.haller',
    rank: 'Funktionär',
    rankLevel: 6,
    position: 'Senior-Partner · Haller & Partner',
    influence: 'Hoch',
    loyalty: 'Bestätigt',
    followers: 198,
    following: 264,
    bio: 'Berater. Vermittler. Brückenbauer.',
    publicParole: 'Vernetzung ist alles.',
    privateHint: 'Strippenzieher des Konsiliums. Verwaltet die „Haller & Partner Treuhand GmbH" — Zahlungsweg für Beraterhonorare.',
    joinedYear: 2011,
    accentColor: '#7e22ce',
    initials: 'VH',
    status: 'Aktiv',
    location: 'Sektor A0 / Brüssel / Wien',
    sector: 'A0',
  },
  {
    id: 'greuling',
    name: 'Dr. Antonia Greuling',
    handle: '@a.greuling',
    rank: 'Zivilist',
    rankLevel: 1,
    position: 'Externe Beobachterin · Account gelöscht',
    influence: 'Gering',
    loyalty: 'Beobachtet',
    followers: 0,
    following: 0,
    bio: '[Profil von offizieller Seite entfernt]',
    publicParole: '[nicht freigegeben]',
    privateHint: 'Investigativ-Journalistin bei einem oppositionellen Medium. Telefonbucheintrag auf Daniels Gerät: „Laura". Sie sucht das verlorene Handy.',
    joinedYear: 2018,
    accentColor: '#0c0a09',
    initials: 'AG',
    status: 'Gesperrt',
    location: 'Sektor C3 / A0',
    sector: 'C3',
  },
  {
    id: 'staatspartei',
    name: 'Staatspartei · PES',
    handle: '@pes.official',
    rank: 'Direktor',
    rankLevel: 7,
    position: 'Offizielle Stimme der Partei',
    influence: 'Hoch',
    loyalty: 'Bestätigt',
    followers: 8240,
    following: 12,
    bio: 'Staatspartei der Allianz. Projektstaat · Einheit · Sicherheit.',
    publicParole: 'Stabilität durch Struktur. Fortschritt durch Verantwortung.',
    privateHint: '',
    joinedYear: 2022,
    accentColor: '#1d9bf0',
    initials: 'SP',
    status: 'Aktiv',
    location: 'Zentrale, Sektor A0',
    sector: 'A0',
  },
];

export const currentUser = {
  id: 'seidt',
  handle: '@d.seidt',
  displayName: 'Dr. Daniel Seidt',
  rank: 'Minister' as Rank,
  rankLevel: 9,
  loyalty: 'In Prüfung' as Loyalty,
  suspicion: 8,
};

export const posts: Post[] = [
  {
    id: 'p-staatspartei-pes-1',
    authorId: 'staatspartei',
    timestamp: '1h',
    text: 'Stabilität entsteht nicht durch Zufall, sondern durch vorausschauende Planung. Mit modernen Datenanalysen und einer effizienten Projektsteuerung schaffen wir ein sicheres, leistungsfähiges Deutschland – heute und für kommende Generationen.\n\nGemeinsam für Einheit und Sicherheit.\n\n#PES #Einheit #Sicherheit',
    likes: 312,
    retweets: 87,
    replies: 14,
    clearance: 'ÖFFENTLICH',
    comments: [
      { author: 'C. Reitmair', authorRank: 'Minister', text: 'Klare Linie. Unterstütze ich vollumfänglich.' },
      { author: 'L. Prack', authorRank: 'Direktor', text: 'Wirtschaftliche Sicherheit ist Sicherheit. Richtig.' },
    ],
  },
  {
    id: 'p-official',
    authorId: 'klingspor',
    timestamp: '2h',
    text: 'Genossinnen und Genossen, heute jährt sich der Gründungstag der Allianz zum 47. Mal. In schwierigen Zeiten halten wir zusammen. Wer aus der Reihe tanzt, schadet der Sache aller.',
    likes: 412,
    retweets: 89,
    replies: 23,
    pinned: true,
    clearance: 'INTERN',
    clueId: 'vox-kommun:klingspor-drohung',
    comments: [
      { author: 'V. Halstenbeck', authorRank: 'Vizeführer', text: 'Danke, Patriarch. Auf die nächsten 47.' },
      { author: 'F. Bellmer', authorRank: 'Minister', text: 'In Verbundenheit. F.W.B.' },
      { author: 'L. Prack', authorRank: 'Direktor', text: 'Pflichtschuldig notiert.' },
    ],
    hint: '„Wer aus der Reihe tanzt" — die Formulierung ist nicht allgemein. Sie meint jemand Konkretes.',
  },
  {
    id: 'p-seidt-family',
    authorId: 'seidt',
    timestamp: '5h',
    text: 'Abend an der Bergstation. Die Kinder genießen die Ruhe, ich die Stille. Danke an alle, die mich in diesen Tagen tragen. Loyalität beginnt zu Hause.',
    imageCaption: 'Sonnenuntergang über Sektor A7 · Bergstation Privatresidenz',
    imageColor: 'linear-gradient(135deg, #1d9bf0 0%, #7856ff 50%, #a855f7 100%)',
    likes: 87,
    retweets: 12,
    replies: 8,
    location: 'Bergstation Privatresidenz',
    clearance: 'INTERN',
    clueId: 'vox-kommun:seidt-bergstation',
    comments: [
      { author: 'M. Seidt', authorRank: 'Mitglied', text: 'Genieß die Zeit, Daniel. Du hast es verdient.' },
      { author: 'T. Siemons', authorRank: 'Vizeminister', text: 'Gleiche Location wie immer. Nächste Woche?' },
      { author: 'V. Haller', authorRank: 'Funktionär', text: '👍' },
    ],
    hint: '„Gleiche Location" — Chiffre „ARGOS-4" und das Bergstation-Wochenendhaus. Siemons kommentiert das öffentlich. Mutig.',
  },
  {
    id: 'p-vehlow-quiet',
    authorId: 'vehlow',
    timestamp: '8h',
    text: 'Q1/Q2 abgeschlossen. Der Apparat läuft. Wer seine Hausaufgaben nicht macht, wird nicht beschützt.',
    likes: 12,
    retweets: 3,
    replies: 2,
    clearance: 'GEHEIM',
    comments: [
      { author: 'T. Beilschmidt', authorRank: 'Funktionär', text: 'Bestätigt. Listen angepasst.' },
      { author: 'S. Lugner', authorRank: 'Direktor', text: 'Quellen ausgewertet. Daten sauber.' },
    ],
    hint: '„Listen angepasst" — wer wird observiert, wer fliegt raus? Hier entscheidet sich der operative Bestand.',
  },
  {
    id: 'p-bellmer-event',
    authorId: 'bellmer',
    timestamp: '12h',
    text: 'Heute beim Festakt der Wehrakademie Sektor F2. Unsere Offiziere verdienen Anerkennung, keine Sonntagsreden.',
    imageCaption: 'Offizielles Gruppenfoto · Offiziere und Ministerialbeamte',
    imageColor: 'linear-gradient(135deg, #1e3a8a 0%, #0f172a 100%)',
    likes: 256,
    retweets: 45,
    replies: 18,
    clearance: 'ÖFFENTLICH',
    comments: [
      { author: 'C. Reitmair', authorRank: 'Minister', text: 'Kamerad. Auf die nächsten 30 Jahre.' },
      { author: 'T. Kaltenborn', authorRank: 'Vizeminister', text: 'Parlament steht hinter Ihnen, Direktor.' },
    ],
  },
  {
    id: 'p-siemons-donations',
    authorId: 'siemons',
    timestamp: '1d',
    text: 'Q1 abgeschlossen, Q2 läuft. Allen Förderinnen und Förderern: euer Beitrag fließt dorthin, wo er hingehört — direkt in die politische Bildung. INITIATIVE 2030 ist transparent und sauber.',
    likes: 34,
    retweets: 7,
    replies: 5,
    clearance: 'INTERN',
    comments: [
      { author: 'M. Seidt', authorRank: 'Mitglied', text: 'Stolz auf 312.000 Credits aus Sektor E2! Weiter so.' },
      { author: 'T. Siemons', authorRank: 'Vizeminister', text: '@m.seidt Vorbildlich. Wir melden uns wegen der nächsten Veranstaltung.' },
    ],
    hint: 'Sektor-E2-Spenden — vergleiche die Buchungslisten in der Files-App. Die offiziellen Empfänger und die tatsächlichen Konten sind nicht identisch.',
  },
  {
    id: 'p-prack-economy',
    authorId: 'prack',
    timestamp: '2d',
    text: 'Vergabeverfahren HYDRA auf der Zielgeraden. Wirtschaftliche Sicherheit ist Sicherheit. Ich danke den beteiligten Häusern für die gewohnt saubere Zusammenarbeit.',
    imageCaption: 'Konferenzraum WIDI · holografische Projektionsfläche',
    imageColor: 'linear-gradient(135deg, #7e22ce 0%, #1e1b4b 100%)',
    likes: 78,
    retweets: 15,
    replies: 6,
    location: 'WIDI · Sektor A0',
    clearance: 'VERTRAULICH',
    comments: [
      { author: 'K. Kahlen', authorRank: 'Funktionär', text: 'Auf eine weiterhin vertrauensvolle Partnerschaft.' },
      { author: 'R. Senger', authorRank: 'Funktionär', text: 'Rechtlich geprüft. Alles im Rahmen.' },
    ],
    hint: '„Rechtlich geprüft" — die vergaberechtliche Bewertung von Dr. Senger ist 17 Seiten lang. Sie hat sie gelesen, du nicht. Noch nicht.',
  },
  {
    id: 'p-staatspartei-pes-2',
    authorId: 'staatspartei',
    timestamp: '2d',
    text: 'Unsere Projektarchitektur verbindet Verwaltung, Wissenschaft und Innovation. Weniger Bürokratie, schnellere Entscheidungen und eine verlässliche staatliche Steuerung sorgen dafür, dass Herausforderungen erkannt werden, bevor sie zu Krisen werden.\n\nFortschritt braucht Struktur.\n\n#Projektstaat #Zukunft #PES',
    likes: 198,
    retweets: 42,
    replies: 9,
    clearance: 'ÖFFENTLICH',
    comments: [
      { author: 'T. Kaltenborn', authorRank: 'Vizeminister', text: 'Endlich wird Verwaltung wieder als Werkzeug verstanden.' },
      { author: 'B. Vehlow', authorRank: 'Direktor', text: 'Struktur schlägt Aktionismus.' },
    ],
  },
  {
    id: 'p-kaltenborn-unity',
    authorId: 'kaltenborn',
    timestamp: '2d',
    text: 'Heute im Parlament: drei Oppositionsanträge zur inneren Sicherheit abgeschmettert. Unsere Linie ist klar, unsere Mehrheit steht. Wer das infrage stellt, hat den Ernst der Lage nicht verstanden.',
    likes: 189,
    retweets: 34,
    replies: 12,
    clearance: 'ÖFFENTLICH',
    comments: [
      { author: 'F. Brandl', authorRank: 'Funktionär', text: 'Klartext. Vermisst man manchmal.' },
      { author: 'B. Vehlow', authorRank: 'Direktor', text: 'Nicht jeder Antrag verdient eine Antwort.' },
    ],
  },
  {
    id: 'p-haller-dinner',
    authorId: 'haller',
    timestamp: '2d',
    text: 'Spätdinner mit alten Freunden. Manches bespricht man besser bei einem guten Glas Wein als in einem Sitzungssaal. Diskretion ist die höchste Form des Respekts.',
    imageCaption: 'Weingläser · warmes Neon-Licht · keine Gesichter erkennbar',
    imageColor: 'linear-gradient(135deg, #c79081 0%, #dfa579 100%)',
    likes: 44,
    retweets: 8,
    replies: 4,
    location: 'Atelier B. · Sektor C3',
    clearance: 'INTERN',
    comments: [
      { author: 'D. Seidt', authorRank: 'Minister', text: 'Danke für den Abend.' },
      { author: 'B. Hollweg', authorRank: 'Funktionär', text: 'Wird nicht das letzte Mal gewesen sein.' },
    ],
    hint: '„Atelier B., Sektor C3" — ein vermeintlicher Weingalerie-Standort, den Viktor Haller als Treffpunkt nutzt. Suche ihn in der Maps-App.',
  },
  {
    id: 'p-beilschmidt-method',
    authorId: 'beilschmidt',
    timestamp: '3d',
    text: 'Frühe Schicht. Wer zu spät kommt, den bestraft das Leben.',
    likes: 8,
    retweets: 1,
    replies: 1,
    clearance: 'GEHEIM',
    comments: [
      { author: 'T. Beilschmidt', authorRank: 'Funktionär', text: '(Selbst-Kommentar) Listen-Update erfolgt um 09:00.' },
    ],
    hint: '„Listen-Update" — er meint die PROMETHEUS-Zielpersonenliste. Du hast Zugriff auf das verschlüsselte PDF. Noch nicht.',
  },
  {
    id: 'p-vizefuehrer-speech',
    authorId: 'vizefuehrer',
    timestamp: '3d',
    text: 'Die Allianz dankt ihren Dienern. Heute Abend habe ich den Sicherheitsapparat empfangen. Was wir tun, tun wir für die Menschen — auch wenn sie es nicht immer verstehen.',
    likes: 743,
    retweets: 156,
    replies: 45,
    pinned: true,
    clearance: 'ÖFFENTLICH',
    comments: [
      { author: 'V. Brandt', authorRank: 'OBERSTER FÜHRER', text: 'In Verbundenheit.' },
      { author: 'B. Foht', authorRank: 'Vizeminister', text: 'Zentrale und SD arbeiten Hand in Hand.' },
    ],
  },
  {
    id: 'p-kahlen-visit',
    authorId: 'kahlen',
    timestamp: '3d',
    text: 'Werksbesuch in Sektor F2. Unsere Drohnensysteme sind das Rückgrat der europäischen Sicherheit. Stolz auf jedes Team-Mitglied.',
    imageCaption: 'Hallenmontage · Tarnfarben · Firmenlogo WARECOM',
    imageColor: 'linear-gradient(135deg, #1f2937 0%, #0c0a09 100%)',
    likes: 102,
    retweets: 22,
    replies: 9,
    location: 'WARECOM Werk Süd · Sektor F2',
    clearance: 'INTERN',
    comments: [
      { author: 'C. Reitmair', authorRank: 'Minister', text: 'Staat und Industrie. Auf Augenhöhe.' },
      { author: 'L. Prack', authorRank: 'Direktor', text: 'Wertungs-Matrix: saubere Punktzahl. 👍' },
    ],
    hint: '„Wertungs-Matrix" — der entscheidende Hinweis auf die manipulierte HYDRA-Vergabe.',
  },
  {
    id: 'p-foht-warning',
    authorId: 'foht',
    timestamp: '4d',
    text: 'Verfahrenstreue ist keine Pedanterie, sie ist die Grundlage unseres Handelns. Ich erinnere alle Direktorate an die Pflicht zur lückenlosen Dokumentation.',
    likes: 19,
    retweets: 4,
    replies: 3,
    clearance: 'INTERN',
    comments: [
      { author: 'C. Pellner', authorRank: 'Funktionär', text: 'Vermerk intern erfolgt.' },
      { author: 'S. Brorsen', authorRank: 'Funktionär', text: 'Personalakten werden entsprechend angepasst.' },
    ],
    hint: 'Foht ist mutig — sie fordert „lückenlose Dokumentation" ein, während um sie herum Akten verschwinden.',
  },
  {
    id: 'p-lugner-data',
    authorId: 'lugner',
    timestamp: '4d',
    text: 'Auswertungen abgeschlossen. Drei Quellen verwertbar, zwei brauchen Nachgang. Datenfusion läuft.',
    likes: 6,
    retweets: 1,
    replies: 0,
    clearance: 'STRENG GEHEIM',
    comments: [],
    hint: '„Datenfusion" — die Konstruktion gefälschter Bezugsprofile für die PROMETHEUS-Observationen.',
  },
  {
    id: 'p-pellner-protect',
    authorId: 'pellner',
    timestamp: '4d',
    text: 'Wieder ein langer Tag. Wer den Apparat am Laufen hält, wird nicht beklatscht — und nicht bestraft. Das reicht mir.',
    likes: 22,
    retweets: 3,
    replies: 2,
    location: 'SD · Sektor A0',
    clearance: 'VERTRAULICH',
    comments: [
      { author: 'B. Vehlow', authorRank: 'Direktor', text: 'Still halten ist auch eine Leistung.' },
      { author: 'D. Seidt', authorRank: 'Minister', text: 'Danke, Corinna.' },
    ],
    hint: 'Pellner ist die Einzige im engsten Kreis, die Zugang zur PROMETHEUS-Direktive hatte — und sie hat sie nicht gelöscht.',
  },
  {
    id: 'p-vehlow-list',
    authorId: 'vehlow',
    timestamp: '5d',
    text: '27 Profile. Alle ausgewertet. Endabstimmung in dieser Woche.',
    likes: 4,
    retweets: 1,
    replies: 1,
    clearance: 'STRENG GEHEIM',
    comments: [
      { author: 'T. Beilschmidt', authorRank: 'Funktionär', text: 'Quellenmaterial abgesichert. Drei Klarnamen ergänzt — Z02 abgehakt.' },
      { author: 'S. Lugner', authorRank: 'Direktor', text: 'Quellen-TKÜ läuft. Daten sauber.' },
    ],
    hint: '„27 Profile" und „Z02 abgehakt" — das ist PROMETHEUS. Z02 ist ein verstorbener Investigativ-Journalist. Er ist „abgehakt".',
  },
  {
    id: 'p-siemons-s4',
    authorId: 'siemons',
    timestamp: '5d',
    text: 'Pakete fertig. ARGOS-4. Übergabe nächste Woche, gleiche Location. Diskretion ist alles.',
    likes: 1,
    retweets: 0,
    replies: 1,
    location: 'Sektor E5',
    clearance: 'GEHEIM',
    comments: [
      { author: 'D. Seidt', authorRank: 'Minister', text: 'Bestätigt.' },
      { author: 'B. Hollweg', authorRank: 'Funktionär', text: 'Empfänger instruiert. Grüße.' },
    ],
    hint: '„ARGOS-4" = 4. Quartals-Ausgleichszahlung. „Gleiche Location" = Bergstation-Wochenendhaus.',
  },
  {
    id: 'p-leonie-critical',
    authorId: 'l.seidt',
    timestamp: '7d',
    text: 'Als Strafrechtlerin beobachte ich mit Sorge, wie der Ausnahme-Zustand zur Regel wird. Die Allianz braucht keine Sonderbefugnisse auf Dauer — sie braucht Vertrauen in ihre Institutionen.',
    likes: 8,
    retweets: 2,
    replies: 3,
    location: 'Sektor C9',
    clearance: 'ÖFFENTLICH',
    comments: [
      { author: 'T. Kaltenborn', authorRank: 'Vizeminister', text: 'Kollegin, Sie sind parteilos unterwegs. Vorsicht.' },
      { author: 'D. Seidt', authorRank: 'Minister', text: '(still)' },
    ],
    hint: 'Leonie Seidt — Daniels Schwester. Sie hat 2024 in einem öffentlichen Medium einen Artikel über Befugniss-Missbrauch veröffentlicht.',
  },
  {
    id: 'p-staatspartei-pes-3',
    authorId: 'staatspartei',
    timestamp: '9d',
    text: 'Verantwortungsvolle Politik bedeutet, Entwicklungen frühzeitig zu erkennen und Lösungen rechtzeitig umzusetzen. Mit präzisen Prognosen, moderner Verwaltung und einem klaren Kurs stärken wir Zusammenhalt, Stabilität und Zukunftsfähigkeit unseres Landes.\n\n#GemeinsamStark #PES #Zukunft',
    likes: 241,
    retweets: 58,
    replies: 11,
    clearance: 'ÖFFENTLICH',
    comments: [
      { author: 'F. Bellmer', authorRank: 'Minister', text: 'Genau der Kurs, den das Land jetzt braucht.' },
    ],
  },
  {
    id: 'p-hollweg-stiftung',
    authorId: 'hollweg',
    timestamp: '9d',
    text: 'Manche Wege führen über mehr als drei Ecken. Wer über Jahrzehnte im Geschäft ist, weiß: Treuhand ist eine Frage des Vertrauens, nicht der Geographie.',
    likes: 6,
    retweets: 1,
    replies: 1,
    location: 'Sektor A0',
    clearance: 'INTERN',
    comments: [
      { author: 'T. Siemons', authorRank: 'Vizeminister', text: 'Treuhand ist alles. 👍' },
    ],
    hint: '„Treuhand" und „Geographie" — Bert Hollweg wickelt Zahlungen über die Haller-Treuhand und eine Offshore-Stiftung „HOFFMANN TRUST" ab.',
  },
  {
    id: 'p-locked-fuehrer',
    authorId: 'fuehrer',
    timestamp: '5d',
    text: '[ ZUGRIFF VERWEIGERT — Freigabe erfordert Stufe 10 · OBERSTER FÜHRER ]',
    likes: 0,
    locked: true,
    requiredRank: 'OBERSTER FÜHRER',
    clearance: 'STRENG GEHEIM',
    comments: [],
    hint: 'Du hast den höchsten nicht-sichtbaren Rang nicht. Wer seine Worte liest, weiß mehr als die gesamte Allianz.',
  },
  {
    id: 'p-locked-seidt-private',
    authorId: 'seidt',
    timestamp: '12d',
    text: '[ ZUGRIFF VERWEIGERT — Freigabe erfordert Rang „Minister" ]',
    likes: 0,
    locked: true,
    requiredRank: 'Minister',
    clearance: 'STRENG GEHEIM',
    comments: [],
    hint: 'Drei Entwürfe im Postausgang, die er nie abgeschickt hat. Einer an „Laura". Einer an seinen Vater. Einer an seine Schwester.',
  },
  {
    id: 'p-greuling-ghost',
    authorId: 'greuling',
    timestamp: '30d',
    text: '[ ACCOUNT GELÖSCHT — ehemalige Zuordnung: investigatives Medium ]',
    likes: 0,
    locked: true,
    requiredRank: 'Zivilist',
    comments: [],
    hint: '„Laura" aus Daniels Nachrichtenverlauf. Sie hat die Story zu einem verstorbenen Journalisten redaktionell betreut. Du hältst das Gerät, nach dem sie sucht.',
  },
];

export const notifications = [
  {
    id: 'n1',
    type: 'like' as const,
    actor: 'Viktor Haller',
    target: 'deinen Beitrag „Diskretion ist die höchste Form…"',
    time: 'vor 4 Min.',
    icon: 'heart',
  },
  {
    id: 'n2',
    type: 'comment' as const,
    actor: 'Britta Vehlow',
    target: '„Stille ist eine Tugend."',
    time: 'vor 22 Min.',
    icon: 'comment',
    text: 'Einverstanden. Melde dich.',
  },
  {
    id: 'n3',
    type: 'system' as const,
    actor: 'VOX KOMMUN',
    target: 'Loyalitätsprüfung Q2/2026 wurde angestoßen',
    time: 'heute · 08:00',
    icon: 'shield',
  },
];

export const trending = [
  { tag: '#Allianz47', posts: 4712 },
  { tag: '#Loyalität', posts: 3100 },
  { tag: '#Initiative2030', posts: 1900 },
  { tag: '#InnereSicherheit', posts: 14200 },
  { tag: '#FamilienDerAllianz', posts: 2800 },
  { tag: '#PROMETHEUS', posts: 847 },
  { tag: '#HYDRA', posts: 234 },
];

export const suggestionAccounts = [
  { id: 'klingspor', reason: 'Empfohlen wegen Rang' },
  { id: 'vizefuehrer', reason: 'Aktiv in deinem Sektor' },
  { id: 'seidt', reason: 'Beliebt bei Mitgliedern' },
];