import {
  Dumbbell,
  Bike,
  Footprints,
  Mountain,
  Waves,
  Snowflake,
  PersonStanding,
  Swords,
  Music,
  Volleyball,
  Trophy,
  Anchor,
  type LucideIcon,
} from 'lucide-react';
import type { IconKey, SavedRoute, Workout, WorkoutProfile } from './types';

export const BRAND = '#FF5722';
export const BRAND_LIGHT = '#FF8A65';

export const STORAGE_KEY_THEME = 'fitness-theme';
export const STORAGE_KEY_ROUTES = 'fitness-saved-routes';
export const STORAGE_KEY_LAST_STARTED = 'fitness-last-started';
export const MAX_ROUTES = 20;
export const DEFAULT_LAST_STARTED_ID = 'push';

export const FILTER_LABELS: { label: string; profile: WorkoutProfile | 'all' }[] = [
  { label: 'Alle', profile: 'all' },
  { label: 'Outdoor', profile: 'outdoor' },
  { label: 'Kraft', profile: 'strength' },
  { label: 'Cardio', profile: 'cardio' },
  { label: 'Beweglichkeit', profile: 'flex' },
  { label: 'Sport', profile: 'sport' },
  { label: 'Wasser', profile: 'water' },
];

export const ICONS: Record<IconKey, LucideIcon> = {
  dumbbell: Dumbbell,
  bike: Bike,
  footprints: Footprints,
  mountain: Mountain,
  waves: Waves,
  snowflake: Snowflake,
  person: PersonStanding,
  swords: Swords,
  music: Music,
  volleyball: Volleyball,
  trophy: Trophy,
  anchor: Anchor,
};

export const WORKOUTS: Workout[] = [
  {
    id: 'push', title: 'Push-Tag', desc: 'Brust, Schulter, Trizeps',
    iconKey: 'dumbbell', profile: 'strength',
    speedKmh: 0, kcalPerMin: 6, waterMlPerHour: 350,
    dur: '55 min', level: 'Mittel', kcal: 420, grad: ['#FF5722', '#FF8A65'],
    exercises: [
      { name: 'Bankdrücken', sets: '4 × 8', muscle: 'Brust', rest: '90s' },
      { name: 'Schulterdrücken', sets: '4 × 10', muscle: 'Schulter', rest: '75s' },
      { name: 'Seitheben', sets: '3 × 12', muscle: 'Seitliche Schulter', rest: '60s' },
      { name: 'Trizeps-Dips', sets: '3 × 12', muscle: 'Trizeps', rest: '60s' },
      { name: 'French Press', sets: '3 × 10', muscle: 'Trizeps', rest: '60s' },
    ],
  },
  {
    id: 'pull', title: 'Pull-Tag', desc: 'Rücken, Bizeps, Unterarme',
    iconKey: 'dumbbell', profile: 'strength',
    speedKmh: 0, kcalPerMin: 6, waterMlPerHour: 350,
    dur: '60 min', level: 'Mittel', kcal: 380, grad: ['#5C6BC0', '#9FA8DA'],
    exercises: [
      { name: 'Klimmzüge', sets: '4 × max', muscle: 'Lats, Bizeps', rest: '90s' },
      { name: 'Langhantelrudern', sets: '4 × 8', muscle: 'Rückenmitte', rest: '90s' },
      { name: 'Latziehen', sets: '3 × 12', muscle: 'Latissimus', rest: '75s' },
      { name: 'Bizeps-Curls', sets: '3 × 12', muscle: 'Bizeps', rest: '60s' },
      { name: 'Hammer-Curls', sets: '3 × 12', muscle: 'Brachialis', rest: '60s' },
    ],
  },
  {
    id: 'legs', title: 'Beine & Core', desc: 'Quadrizeps, Beinbeuger, Bauch',
    iconKey: 'dumbbell', profile: 'strength',
    speedKmh: 0, kcalPerMin: 7, waterMlPerHour: 400,
    dur: '50 min', level: 'Schwer', kcal: 510, grad: ['#26A69A', '#80CBC4'],
    exercises: [
      { name: 'Kniebeugen', sets: '5 × 5', muscle: 'Quadrizeps, Glutes', rest: '120s' },
      { name: 'Ausfallschritte', sets: '3 × 10 / Seite', muscle: 'Beine, Glutes', rest: '75s' },
      { name: 'Beinpresse', sets: '4 × 10', muscle: 'Quadrizeps', rest: '90s' },
      { name: 'Plank', sets: '3 × 60s', muscle: 'Core', rest: '45s' },
      { name: 'Russian Twists', sets: '3 × 20', muscle: 'Schräge Bauch', rest: '45s' },
    ],
  },
  {
    id: 'hiit', title: 'Cardio HIIT', desc: 'Hochintensives Intervall',
    iconKey: 'dumbbell', profile: 'cardio',
    speedKmh: 0, kcalPerMin: 12, waterMlPerHour: 700,
    dur: '25 min', level: 'Leicht', kcal: 320, grad: ['#EF5350', '#FF8A80'],
    exercises: [
      { name: 'Burpees', sets: '4 × 30s', muscle: 'Ganzkörper', rest: '30s' },
      { name: 'Mountain Climbers', sets: '4 × 30s', muscle: 'Core, Cardio', rest: '30s' },
      { name: 'Jumping Jacks', sets: '4 × 40s', muscle: 'Cardio', rest: '20s' },
      { name: 'High Knees', sets: '4 × 30s', muscle: 'Beine, Cardio', rest: '30s' },
      { name: 'Squat Jumps', sets: '4 × 12', muscle: 'Beine, Cardio', rest: '30s' },
    ],
  },
  {
    id: 'yoga', title: 'Yoga Flow', desc: 'Beweglichkeit & Balance',
    iconKey: 'dumbbell', profile: 'flex',
    speedKmh: 0, kcalPerMin: 3, waterMlPerHour: 300,
    dur: '40 min', level: 'Leicht', kcal: 180, grad: ['#AB47BC', '#CE93D8'],
    exercises: [
      { name: 'Sonnengruß', sets: '3 × 1', muscle: 'Ganzkörper', rest: '30s' },
      { name: 'Krieger I & II', sets: '2 × 45s / Seite', muscle: 'Beine, Balance', rest: '15s' },
      { name: 'Herabschauender Hund', sets: '3 × 30s', muscle: 'Rücken, Beine', rest: '15s' },
      { name: 'Kindhaltung', sets: '2 × 60s', muscle: 'Entspannung', rest: '—' },
      { name: 'Savasana', sets: '1 × 5 min', muscle: 'Entspannung', rest: '—' },
    ],
  },
  {
    id: 'bike', title: 'Rad Outdoor', desc: 'Ausdauer & Beinkraft',
    iconKey: 'bike', profile: 'outdoor',
    speedKmh: 22, kcalPerMin: 8, waterMlPerHour: 600,
    dur: '60 min', level: 'Mittel', kcal: 480, grad: ['#10B981', '#34D399'],
    exercises: [
      { name: 'Aufwärmen', sets: '10 min', muscle: 'Flach, lockeres Tempo', rest: '—' },
      { name: 'Bergauf-Intervalle', sets: '4 × 3 min', muscle: 'Anstieg, hohe Trittfrequenz', rest: '2 min' },
      { name: 'Flachstrecke', sets: '20 min', muscle: 'Gleichmäßiges Tempo', rest: '—' },
      { name: 'Sprint-Intervalle', sets: '5 × 1 min', muscle: 'Max. Anstrengung', rest: '90s' },
      { name: 'Cool-Down', sets: '10 min', muscle: 'Locker ausrollen', rest: '—' },
    ],
  },
  {
    id: 'run', title: 'Laufen', desc: 'Cardio & Ausdauer',
    iconKey: 'footprints', profile: 'outdoor',
    speedKmh: 10.5, kcalPerMin: 9.5, waterMlPerHour: 650, pace: true,
    dur: '45 min', level: 'Mittel', kcal: 420, grad: ['#3B82F6', '#60A5FA'],
    exercises: [
      { name: 'Aufwärmen', sets: '5 min', muscle: 'Gehen, lockeres Joggen', rest: '—' },
      { name: '5 km Dauerlauf', sets: '25 min', muscle: 'Gleichmäßiges Tempo', rest: '—' },
      { name: 'Tempo-Intervalle', sets: '4 × 400m', muscle: '90% Max-Pace', rest: '90s' },
      { name: 'Cooldown-Joggen', sets: '5 min', muscle: 'Locker auslaufen', rest: '—' },
      { name: 'Dehnen', sets: '5 min', muscle: 'Beine, Hüfte', rest: '—' },
    ],
  },
  {
    id: 'hike', title: 'Wandern', desc: 'Natur & leichte Ausdauer',
    iconKey: 'mountain', profile: 'outdoor',
    speedKmh: 4.5, kcalPerMin: 5, waterMlPerHour: 400,
    dur: '90 min', level: 'Leicht', kcal: 320, grad: ['#92400E', '#D97706'],
    exercises: [
      { name: 'Loslaufen', sets: '10 min', muscle: 'Flach, Einlaufen', rest: '—' },
      { name: 'Anstieg', sets: '30 min', muscle: 'Moderate Steigung', rest: '—' },
      { name: 'Plateau-Phase', sets: '20 min', muscle: 'Gleichmäßiges Tempo', rest: '—' },
      { name: 'Abstieg', sets: '20 min', muscle: 'Kontrolliert bergab', rest: '—' },
      { name: 'Cool-Down & Dehnen', sets: '10 min', muscle: 'Beine, Rücken', rest: '—' },
    ],
  },
  {
    id: 'mtb', title: 'Mountainbike', desc: 'Offroad & Trails',
    iconKey: 'bike', profile: 'outdoor',
    speedKmh: 18, kcalPerMin: 11, waterMlPerHour: 800,
    dur: '75 min', level: 'Schwer', kcal: 620, grad: ['#16A34A', '#4ADE80'],
    exercises: [
      { name: 'Warm-up Trails', sets: '10 min', muscle: 'Lockeres Fahren', rest: '—' },
      { name: 'Bergauf-Intervalle', sets: '5 × 4 min', muscle: 'Steiler Anstieg', rest: '2 min' },
      { name: 'Downhill-Sektionen', sets: '6 × 3 min', muscle: 'Technisch, schnell', rest: '2 min' },
      { name: 'Flachpassagen', sets: '20 min', muscle: 'Gleichmäßiges Tempo', rest: '—' },
      { name: 'Cool-Down', sets: '10 min', muscle: 'Locker ausrollen', rest: '—' },
    ],
  },
  {
    id: 'trailrun', title: 'Trail Running', desc: 'Wald- & Bergpfad',
    iconKey: 'footprints', profile: 'outdoor',
    speedKmh: 8.5, kcalPerMin: 12, waterMlPerHour: 700, pace: true,
    dur: '50 min', level: 'Mittel', kcal: 480, grad: ['#059669', '#10B981'],
    exercises: [
      { name: 'Warm-up', sets: '5 min', muscle: 'Langsamer Trab', rest: '—' },
      { name: 'Hügellauf', sets: '6 × 3 min', muscle: 'Bergauf, steile Passagen', rest: '90s' },
      { name: 'Downhill-Lauf', sets: '4 × 2 min', muscle: 'Kontrolliert bergab', rest: '60s' },
      { name: 'Waldpfad-Flat', sets: '15 min', muscle: 'Gleichmäßiges Tempo', rest: '—' },
      { name: 'Cooldown', sets: '5 min', muscle: 'Gehen & stretchen', rest: '—' },
    ],
  },
  {
    id: 'swim', title: 'Schwimmen', desc: 'Ganzkörper-Cardio',
    iconKey: 'waves', profile: 'water',
    speedKmh: 2.5, kcalPerMin: 10, waterMlPerHour: 0,
    dur: '45 min', level: 'Mittel', kcal: 450, grad: ['#0891B2', '#22D3EE'],
    exercises: [
      { name: 'Aufwärmen', sets: '5 min', muscle: 'Lockeres Kraulen', rest: '—' },
      { name: 'Kraul-Intervalle', sets: '6 × 100m', muscle: 'Ganzkörper', rest: '30s' },
      { name: 'Brustschwimmen', sets: '4 × 50m', muscle: 'Brust, Beine', rest: '30s' },
      { name: 'Rückenschwimmen', sets: '4 × 50m', muscle: 'Rücken, Schultern', rest: '30s' },
      { name: 'Ausschwimmen', sets: '5 min', muscle: 'Lockeres Tempo', rest: '—' },
    ],
  },
  {
    id: 'openwater', title: 'Freiwasser-Schwimmen', desc: 'See oder Meer',
    iconKey: 'waves', profile: 'water',
    speedKmh: 2.2, kcalPerMin: 11, waterMlPerHour: 0,
    dur: '60 min', level: 'Mittel', kcal: 520, grad: ['#0E7490', '#06B6D4'],
    exercises: [
      { name: 'Eingewöhnen', sets: '5 min', muscle: 'Langsam an Temperatur', rest: '—' },
      { name: 'Lange Bahnen', sets: '8 × 300m', muscle: 'Gleichmäßig kraulen', rest: '45s' },
      { name: 'Technik-Fokus', sets: '4 × 100m', muscle: 'Atmung & Zug', rest: '30s' },
      { name: 'Sprint-Steigerung', sets: '3 × 50m', muscle: 'Max-Tempo', rest: '60s' },
      { name: 'Ausschwimmen', sets: '5 min', muscle: 'Locker & Stretching', rest: '—' },
    ],
  },
  {
    id: 'ski', title: 'Skifahren Alpin', desc: 'Piste & Carving',
    iconKey: 'snowflake', profile: 'outdoor',
    speedKmh: 30, kcalPerMin: 9, waterMlPerHour: 500,
    dur: '120 min', level: 'Mittel', kcal: 780, grad: ['#0284C7', '#38BDF8'],
    exercises: [
      { name: 'Aufwärmen', sets: '10 min', muscle: 'Leichte Piste', rest: '—' },
      { name: 'Carving-Übungen', sets: '8 Abfahrten', muscle: 'Beine, Core', rest: '2 min' },
      { name: 'Steile Pisten', sets: '6 Abfahrten', muscle: 'Oberschenkel', rest: '3 min' },
      { name: 'Freie Fahrt', sets: '60 min', muscle: 'Genuss-Abfahrten', rest: '—' },
      { name: 'Cool-Down & Lift', sets: '15 min', muscle: 'Lockeres Fahren', rest: '—' },
    ],
  },
  {
    id: 'langlauf', title: 'Langlauf', desc: 'Skating oder Klassik',
    iconKey: 'snowflake', profile: 'outdoor',
    speedKmh: 12, kcalPerMin: 11, waterMlPerHour: 600,
    dur: '60 min', level: 'Mittel', kcal: 540, grad: ['#1E40AF', '#3B82F6'],
    exercises: [
      { name: 'Warm-up', sets: '10 min', muscle: 'Klassischer Stil', rest: '—' },
      { name: 'Skating-Intervalle', sets: '5 × 3 min', muscle: 'Ganzkörper', rest: '90s' },
      { name: 'Bergauf-Passagen', sets: '4 × 4 min', muscle: 'Beine, Arme', rest: '2 min' },
      { name: 'Lange Loipe', sets: '20 min', muscle: 'Gleichmäßiges Tempo', rest: '—' },
      { name: 'Cool-Down', sets: '5 min', muscle: 'Locker ausklingen', rest: '—' },
    ],
  },
  {
    id: 'kayak', title: 'Kajak', desc: 'Paddeln auf dem See',
    iconKey: 'anchor', profile: 'water',
    speedKmh: 6, kcalPerMin: 7, waterMlPerHour: 500,
    dur: '60 min', level: 'Leicht', kcal: 380, grad: ['#0369A1', '#0EA5E9'],
    exercises: [
      { name: 'Einsetzen & Anlegen', sets: '5 min', muscle: 'Vorbereitung', rest: '—' },
      { name: 'Grundschlag', sets: '15 min', muscle: 'Rumpf, Arme', rest: '—' },
      { name: 'Rundkurs', sets: '20 min', muscle: 'Ausdauer', rest: '—' },
      { name: 'Sprint-Intervalle', sets: '4 × 1 min', muscle: 'Maximalkraft', rest: '90s' },
      { name: 'Rückweg', sets: '15 min', muscle: 'Lockeres Tempo', rest: '—' },
    ],
  },
  {
    id: 'row', title: 'Rudern (Ergometer)', desc: 'Indoor-Row',
    iconKey: 'dumbbell', profile: 'cardio',
    speedKmh: 0, kcalPerMin: 10, waterMlPerHour: 700,
    dur: '30 min', level: 'Mittel', kcal: 320, grad: ['#1E3A8A', '#3B82F6'],
    exercises: [
      { name: 'Aufwärmen', sets: '5 min', muscle: 'Lockeres Rudern', rest: '—' },
      { name: '2000m Time Trial', sets: '1 × 8 min', muscle: 'Ganzkörper', rest: '—' },
      { name: 'Intervalle 500m', sets: '4 × 500m', muscle: 'Max-Pace', rest: '90s' },
      { name: 'Ausdauerblock', sets: '10 min', muscle: 'Stabile Pace', rest: '—' },
      { name: 'Cool-Down', sets: '3 min', muscle: 'Lockeres Rudern', rest: '—' },
    ],
  },
  {
    id: 'rowoutdoor', title: 'Rudern Outdoor', desc: 'Boot auf dem See',
    iconKey: 'anchor', profile: 'outdoor',
    speedKmh: 8, kcalPerMin: 9, waterMlPerHour: 600,
    dur: '60 min', level: 'Mittel', kcal: 480, grad: ['#1E40AF', '#60A5FA'],
    exercises: [
      { name: 'Klarmachen', sets: '5 min', muscle: 'Vorbereitung', rest: '—' },
      { name: 'Aufwärmen', sets: '5 min', muscle: 'Lockeres Rudern', rest: '—' },
      { name: 'Strecke', sets: '30 min', muscle: 'Gleichmäßige Schläge', rest: '—' },
      { name: 'Sprints', sets: '4 × 1 min', muscle: 'Maximalkraft', rest: '2 min' },
      { name: 'Rückweg & Anlegen', sets: '20 min', muscle: 'Locker & Aufräumen', rest: '—' },
    ],
  },
  {
    id: 'pilates', title: 'Pilates', desc: 'Core & Beweglichkeit',
    iconKey: 'person', profile: 'flex',
    speedKmh: 0, kcalPerMin: 4, waterMlPerHour: 250,
    dur: '45 min', level: 'Leicht', kcal: 200, grad: ['#9333EA', '#C084FC'],
    exercises: [
      { name: 'Atemübungen', sets: '5 min', muscle: 'Zwerchfell, Entspannung', rest: '—' },
      { name: 'Hundred', sets: '100 Pumps', muscle: 'Bauch, Atem', rest: '—' },
      { name: 'Roll Up', sets: '3 × 10', muscle: 'Bauch, Wirbelsäule', rest: '30s' },
      { name: 'Single Leg Circles', sets: '2 × 10 / Seite', muscle: 'Hüfte, Core', rest: '30s' },
      { name: 'Cool-Down Stretch', sets: '10 min', muscle: 'Ganzkörper', rest: '—' },
    ],
  },
  {
    id: 'stretch', title: 'Stretching', desc: 'Mobilisation & Recovery',
    iconKey: 'person', profile: 'flex',
    speedKmh: 0, kcalPerMin: 2, waterMlPerHour: 200,
    dur: '20 min', level: 'Leicht', kcal: 60, grad: ['#7C3AED', '#A78BFA'],
    exercises: [
      { name: 'Nacken & Schultern', sets: '3 min', muscle: 'Entspannung', rest: '—' },
      { name: 'Wirbelsäule', sets: '4 min', muscle: 'Rücken, Mobilität', rest: '—' },
      { name: 'Hüfte & Oberschenkel', sets: '5 min', muscle: 'Beine', rest: '—' },
      { name: 'Beine & Waden', sets: '4 min', muscle: 'Unterschenkel', rest: '—' },
      { name: 'Atem-Meditation', sets: '4 min', muscle: 'Entspannung', rest: '—' },
    ],
  },
  {
    id: 'meditation', title: 'Meditation', desc: 'Achtsamkeit & Atem',
    iconKey: 'music', profile: 'flex',
    speedKmh: 0, kcalPerMin: 1, waterMlPerHour: 100,
    dur: '15 min', level: 'Leicht', kcal: 20, grad: ['#BE185D', '#F472B6'],
    exercises: [
      { name: 'Ankommen', sets: '3 min', muscle: 'Atem & Körper', rest: '—' },
      { name: 'Atem-Meditation', sets: '5 min', muscle: 'Achtsamkeit', rest: '—' },
      { name: 'Body-Scan', sets: '5 min', muscle: 'Wahrnehmung', rest: '—' },
      { name: 'Loslassen', sets: '2 min', muscle: 'Gedanken ziehen lassen', rest: '—' },
    ],
  },
  {
    id: 'kickbox', title: 'Kickboxen', desc: 'Cardio & Combat',
    iconKey: 'swords', profile: 'cardio',
    speedKmh: 0, kcalPerMin: 12, waterMlPerHour: 800,
    dur: '50 min', level: 'Schwer', kcal: 560, grad: ['#B91C1C', '#EF4444'],
    exercises: [
      { name: 'Shadowbox-Aufwärmen', sets: '5 min', muscle: 'Technik locker', rest: '—' },
      { name: 'Schlag-Pads', sets: '6 × 3 min', muscle: 'Arme, Schultern', rest: '60s' },
      { name: 'Tritt-Kombinationen', sets: '5 × 3 min', muscle: 'Beine, Core', rest: '60s' },
      { name: 'Sparring', sets: '4 × 3 min', muscle: 'Ganzkörper', rest: '90s' },
      { name: 'Cool-Down', sets: '5 min', muscle: 'Stretching', rest: '—' },
    ],
  },
  {
    id: 'zumba', title: 'Zumba', desc: 'Tanz-Fitness',
    iconKey: 'music', profile: 'cardio',
    speedKmh: 0, kcalPerMin: 9, waterMlPerHour: 550,
    dur: '45 min', level: 'Mittel', kcal: 400, grad: ['#DB2777', '#F472B6'],
    exercises: [
      { name: 'Warm-up-Song', sets: '5 min', muscle: 'Langsame Choreo', rest: '—' },
      { name: 'Salsa-Block', sets: '10 min', muscle: 'Beine, Hüfte', rest: '—' },
      { name: 'Reggaeton', sets: '10 min', muscle: 'Cardio, Core', rest: '—' },
      { name: 'Merengue & Cumbia', sets: '10 min', muscle: 'Ganzkörper', rest: '—' },
      { name: 'Cool-Down-Song', sets: '10 min', muscle: 'Locker & Stretch', rest: '—' },
    ],
  },
  {
    id: 'tennis', title: 'Tennis', desc: 'Einzel oder Doppel',
    iconKey: 'volleyball', profile: 'sport',
    speedKmh: 0, kcalPerMin: 8, waterMlPerHour: 700,
    dur: '60 min', level: 'Mittel', kcal: 480, grad: ['#15803D', '#22C55E'],
    exercises: [
      { name: 'Einspielen', sets: '10 min', muscle: 'Aufwärm-Schläge', rest: '—' },
      { name: 'Grundlinienduell', sets: '20 min', muscle: 'Ausdauer', rest: '—' },
      { name: 'Volleys am Netz', sets: '10 min', muscle: 'Reaktion, Beine', rest: '—' },
      { name: 'Aufschlag-Training', sets: '10 min', muscle: 'Schulter, Core', rest: '—' },
      { name: 'Match', sets: '10 min', muscle: 'Alles zusammen', rest: '—' },
    ],
  },
  {
    id: 'kettlebell', title: 'Kettlebell-Training', desc: 'Functional & Kraft',
    iconKey: 'dumbbell', profile: 'strength',
    speedKmh: 0, kcalPerMin: 11, waterMlPerHour: 550,
    dur: '40 min', level: 'Schwer', kcal: 440, grad: ['#9A3412', '#EA580C'],
    exercises: [
      { name: 'Warm-up Swings', sets: '5 min', muscle: 'Hüfte, Beine', rest: '—' },
      { name: 'Swings', sets: '5 × 20', muscle: 'Posterior Chain', rest: '60s' },
      { name: 'Goblet Squats', sets: '4 × 12', muscle: 'Beine, Core', rest: '60s' },
      { name: 'Turkish Get-Up', sets: '3 × 5 / Seite', muscle: 'Ganzkörper', rest: '90s' },
      { name: 'Clean & Press', sets: '4 × 8', muscle: 'Schultern, Core', rest: '90s' },
    ],
  },
  {
    id: 'crossfit', title: 'CrossFit WOD', desc: 'Variation des Tages',
    iconKey: 'trophy', profile: 'strength',
    speedKmh: 0, kcalPerMin: 14, waterMlPerHour: 800,
    dur: '30 min', level: 'Schwer', kcal: 420, grad: ['#7F1D1D', '#DC2626'],
    exercises: [
      { name: 'Warm-up', sets: '5 min', muscle: 'Mobilität', rest: '—' },
      { name: 'AMRAP 20: Burpees + KB Swings', sets: '20 min', muscle: 'Ganzkörper', rest: '—' },
      { name: 'Wall Balls', sets: '5 × 15', muscle: 'Beine, Schultern', rest: '60s' },
      { name: 'Box Jumps', sets: '5 × 10', muscle: 'Beine, Power', rest: '60s' },
      { name: 'Cool-Down', sets: '5 min', muscle: 'Stretching', rest: '—' },
    ],
  },
  {
    id: 'rope', title: 'Seilspringen', desc: 'Cardio-Klassiker',
    iconKey: 'dumbbell', profile: 'cardio',
    speedKmh: 0, kcalPerMin: 13, waterMlPerHour: 650,
    dur: '20 min', level: 'Mittel', kcal: 260, grad: ['#CA8A04', '#FACC15'],
    exercises: [
      { name: 'Warm-up Springen', sets: '3 min', muscle: 'Locker', rest: '—' },
      { name: 'Basic Jump', sets: '5 × 1 min', muscle: 'Waden, Cardio', rest: '30s' },
      { name: 'Double Unders', sets: '5 × 30s', muscle: 'Power, Beine', rest: '30s' },
      { name: 'High Knees', sets: '4 × 45s', muscle: 'Beine, Cardio', rest: '30s' },
      { name: 'Cool-Down', sets: '2 min', muscle: 'Stretching', rest: '—' },
    ],
  },
  {
    id: 'stairs', title: 'Treppensteigen', desc: 'Stairmaster-Alternative',
    iconKey: 'mountain', profile: 'outdoor',
    speedKmh: 5, kcalPerMin: 13, waterMlPerHour: 700,
    dur: '25 min', level: 'Mittel', kcal: 320, grad: ['#365314', '#84CC16'],
    exercises: [
      { name: 'Lockeres Treppengehen', sets: '5 min', muscle: 'Aufwärmen', rest: '—' },
      { name: 'Schnelle Stufen', sets: '5 × 2 min', muscle: 'Beine, Po', rest: '60s' },
      { name: 'Doppelschritte', sets: '5 × 1 min', muscle: 'Oberschenkel', rest: '60s' },
      { name: 'Tragen von Gewichten', sets: '3 × 3 min', muscle: 'Ganzkörper', rest: '90s' },
      { name: 'Cool-Down', sets: '3 min', muscle: 'Locker runter', rest: '—' },
    ],
  },
  {
    id: 'tanz', title: 'Tanz', desc: 'Freier Tanz',
    iconKey: 'music', profile: 'cardio',
    speedKmh: 0, kcalPerMin: 7, waterMlPerHour: 500,
    dur: '40 min', level: 'Leicht', kcal: 280, grad: ['#6D28D9', '#A78BFA'],
    exercises: [
      { name: 'Warm-up Beats', sets: '5 min', muscle: 'Locker bewegen', rest: '—' },
      { name: 'Freies Tanzen', sets: '30 min', muscle: 'Ganzkörper, Cardio', rest: '—' },
      { name: 'Cool-Down & Atem', sets: '5 min', muscle: 'Entspannung', rest: '—' },
    ],
  },
];

export function buildSeedRoutes(): SavedRoute[] {
  const now = Date.now();
  const HOUR = 3600 * 1000;
  const DAY = 24 * HOUR;
  return [
    {
      id: 'seed_run_1',
      workoutId: 'run',
      workoutTitle: 'Laufen',
      iconKey: 'footprints',
      grad: ['#3B82F6', '#60A5FA'],
      distanceKm: 5.32,
      durationMs: (32 * 60 + 15) * 1000,
      finishedAt: now - 4 * DAY,
    },
    {
      id: 'seed_bike_1',
      workoutId: 'bike',
      workoutTitle: 'Rad Outdoor',
      iconKey: 'bike',
      grad: ['#10B981', '#34D399'],
      distanceKm: 18.4,
      durationMs: 60 * 60 * 1000,
      finishedAt: now - 6 * HOUR,
    },
    {
      id: 'seed_trail_1',
      workoutId: 'trailrun',
      workoutTitle: 'Trail Running',
      iconKey: 'footprints',
      grad: ['#059669', '#10B981'],
      distanceKm: 8.7,
      durationMs: 50 * 60 * 1000,
      finishedAt: now - 2 * DAY,
    },
    {
      id: 'seed_mtb_1',
      workoutId: 'mtb',
      workoutTitle: 'Mountainbike',
      iconKey: 'bike',
      grad: ['#16A34A', '#4ADE80'],
      distanceKm: 22.1,
      durationMs: 75 * 60 * 1000,
      finishedAt: now - 5 * DAY,
    },
  ];
}
