import type { Chat } from './types';

const minutesAgo = (m: number) => new Date(Date.now() - m * 60 * 1000);
const hoursAgo = (h: number) => new Date(Date.now() - h * 60 * 60 * 1000);
const daysAgo = (d: number) => new Date(Date.now() - d * 24 * 60 * 60 * 1000);

export const initialChats: Chat[] = [
  {
    id: 'laura',
    name: 'Laura',
    avatarColor: '#6366F1',
    phone: '+49 30 555 0142',
    about: 'Investigativ-Journalistin',
    lastSeen: 'online',
    unreadCount: 3,
    messages: [
      { id: 'la1', text: 'Du antwortest nicht mehr auf normale Fragen.', timestamp: hoursAgo(3), fromMe: false },
      { id: 'la2', text: 'Ich bin viel unterwegs.', timestamp: hoursAgo(3), fromMe: true, status: 'read' },
      { id: 'la3', text: 'Das ist keine Erklärung, das ist ein Muster.', timestamp: hoursAgo(3), fromMe: false },
      { id: 'la4', text: 'Du interpretierst zu viel hinein.', timestamp: hoursAgo(2.5), fromMe: true, status: 'read' },
      { id: 'la5', text: 'Ich arbeite an einem Text über Einflussstrukturen in Berlin.', timestamp: hoursAgo(2), fromMe: false },
      { id: 'la6', text: 'Das ist gefährlich.', timestamp: hoursAgo(2), fromMe: true, status: 'read' },
      { id: 'la7', text: 'Warum?', timestamp: hoursAgo(1.5), fromMe: false },
      { id: 'la8', text: 'Weil du nicht weißt, wie Dinge zusammenhängen.', timestamp: hoursAgo(1.5), fromMe: true, status: 'read' },
      { id: 'la9', text: 'Oder weil du nicht willst, dass ich es weiß.', timestamp: hoursAgo(1.5), fromMe: false },
      { id: 'la10', text: 'Ich habe jemanden getroffen, der deine Akte kennt.', timestamp: hoursAgo(1), fromMe: false },
      { id: 'la11', text: 'Welche Akte?', timestamp: hoursAgo(1), fromMe: true, status: 'read' },
      { id: 'la12', text: 'Die du nicht kennst.', timestamp: minutesAgo(45), fromMe: false },
      { id: 'la13', text: 'Hör auf damit.', timestamp: minutesAgo(30), fromMe: true, status: 'read' },
      { id: 'la14', text: 'Ich höre erst auf, wenn ich verstehe, warum du dich verändert hast.', timestamp: minutesAgo(20), fromMe: false },
    ],
  },
  {
    id: 'helena',
    name: 'Helena ❤️',
    avatarColor: '#EC4899',
    phone: '+49 30 555 0117',
    about: 'Familie',
    lastSeen: 'online',
    unreadCount: 1,
    messages: [
      { id: 'he1', text: 'Du warst gestern spät noch im Arbeitszimmer.', timestamp: hoursAgo(18), fromMe: false },
      { id: 'he2', text: 'Ich habe noch gelesen.', timestamp: hoursAgo(17), fromMe: true, status: 'read' },
      { id: 'he3', text: 'Du liest immer, wenn du eigentlich nicht schlafen kannst.', timestamp: hoursAgo(17), fromMe: false },
      { id: 'he4', text: 'Vielleicht.', timestamp: hoursAgo(16), fromMe: true, status: 'read' },
      { id: 'he5', text: 'Ist es gerade wieder viel?', timestamp: hoursAgo(16), fromMe: false },
      { id: 'he6', text: 'Es ist… voll.', timestamp: hoursAgo(16), fromMe: true, status: 'read' },
      { id: 'he7', text: 'Das ist dein Standardwort für alles, was dich beschäftigt.', timestamp: hoursAgo(16), fromMe: false },
      { id: 'he8', text: 'Weil es stimmt.', timestamp: hoursAgo(15), fromMe: true, status: 'read' },
      { id: 'he9', text: 'Nick hat dich heute im Flur gesucht.', timestamp: hoursAgo(5), fromMe: false },
      { id: 'he10', text: 'Ich war am Telefon.', timestamp: hoursAgo(5), fromMe: true, status: 'read' },
      { id: 'he11', text: 'Er hat gesagt: „Papa ist da, aber nicht da."', timestamp: hoursAgo(5), fromMe: false },
      { id: 'he12', text: 'Das tut mir leid.', timestamp: hoursAgo(4.5), fromMe: true, status: 'read' },
      { id: 'he13', text: 'Er will einfach nur zehn Minuten echte Zeit.', timestamp: hoursAgo(4.5), fromMe: false },
      { id: 'he14', text: 'Ich weiß.', timestamp: hoursAgo(4.5), fromMe: true, status: 'read' },
      { id: 'he15', text: 'Sonntag gehört ihm.', timestamp: hoursAgo(4), fromMe: true, status: 'read' },
      { id: 'he16', text: 'Nicht nur ihm.', timestamp: hoursAgo(4), fromMe: false },
      { id: 'he17', text: 'Uns.', timestamp: hoursAgo(3.5), fromMe: true, status: 'read' },
      { id: 'he18', text: 'Gut.', timestamp: hoursAgo(3.5), fromMe: false },
    ],
  },
  {
    id: 'familie',
    name: 'Seidt & Anhang 👨‍👩‍👧‍👦',
    avatarColor: '#EC4899',
    isGroup: true,
    about: 'Familiengruppe',
    lastSeen: '',
    unreadCount: 4,
    messages: [
      { id: 'fa1', text: 'Nick hat morgen Projektwoche. Er braucht noch den Ausdruck „Berlin im Wandel".', timestamp: daysAgo(4), fromMe: false, sender: 'Helena' },
      { id: 'fa2', text: 'Liegt auf dem Drucker im Arbeitszimmer.', timestamp: daysAgo(4), fromMe: true, status: 'read' },
      { id: 'fa3', text: 'Ich könnte ihn auf dem Weg zur Kaserne kurz mitnehmen und abgeben.', timestamp: daysAgo(4), fromMe: false, sender: 'Sarah' },
      { id: 'fa4', text: 'Das wäre großartig, danke.', timestamp: daysAgo(4), fromMe: false, sender: 'Helena' },
      { id: 'fa5', text: 'Falls jemand fragt: ich habe mit diesem Drucker nichts zu tun.', timestamp: daysAgo(4), fromMe: false, sender: 'Markus' },
      { id: 'fa6', text: 'Markus, du bist der einzige, der ihn jemals „kalibriert" hat.', timestamp: daysAgo(4), fromMe: false, sender: 'Laura' },
      { id: 'fa7', text: 'Ich optimiere ihn.', timestamp: daysAgo(4), fromMe: false, sender: 'Markus' },
      { id: 'fa8', text: 'Bitte keine technische Optimierung am Familiengerät vor 7 Uhr morgens.', timestamp: daysAgo(4), fromMe: true, status: 'read' },

      { id: 'fa9', text: 'Noch etwas: Lottas Arzttermin wurde verschoben auf Donnerstag.', timestamp: daysAgo(4), fromMe: false, sender: 'Helena' },
      { id: 'fa10', text: 'Ich versuche, es einzurichten.', timestamp: daysAgo(4), fromMe: true, status: 'read' },
      { id: 'fa11', text: 'Wenn du nicht kannst, gehe ich mit.', timestamp: daysAgo(4), fromMe: false, sender: 'Sarah' },
      { id: 'fa12', text: 'Danke euch beiden.', timestamp: daysAgo(4), fromMe: false, sender: 'Helena' },
      { id: 'fa13', text: 'Ich kann danach kurz telefonieren, wegen Nachsorge.', timestamp: daysAgo(4), fromMe: false, sender: 'Laura' },
      { id: 'fa14', text: 'Gern.', timestamp: daysAgo(4), fromMe: false, sender: 'Helena' },

      { id: 'fa15', text: 'Nick hat gefragt, ob du heute zum Vorlesen da bist.', timestamp: daysAgo(3), fromMe: false, sender: 'Helena' },
      { id: 'fa16', text: 'Ich komme später. Dienstlich verzögert.', timestamp: daysAgo(3), fromMe: true, status: 'read' },
      { id: 'fa17', text: 'Er war enttäuscht.', timestamp: daysAgo(3), fromMe: false, sender: 'Helena' },
      { id: 'fa18', text: 'Ich hole es nach.', timestamp: daysAgo(3), fromMe: true, status: 'read' },
      { id: 'fa19', text: 'Ich kann einspringen. Allerdings nur Sachbuchniveau 3.', timestamp: daysAgo(3), fromMe: false, sender: 'Markus' },
      { id: 'fa20', text: 'Das ist für Nick wahrscheinlich schon zu viel Drama.', timestamp: daysAgo(3), fromMe: false, sender: 'Laura' },
      { id: 'fa21', text: 'Unverschämt.', timestamp: daysAgo(3), fromMe: false, sender: 'Markus' },
      { id: 'fa22', text: 'Ich bin heute Abend in Berlin. Ich könnte kurz vorbeikommen.', timestamp: daysAgo(3), fromMe: false, sender: 'Sarah' },
      { id: 'fa23', text: 'Das wäre sehr schön.', timestamp: daysAgo(3), fromMe: false, sender: 'Helena' },

      { id: 'fa24', text: 'Daniel, kannst du mir sagen, ob du am Wochenende wirklich frei hast?', timestamp: daysAgo(3), fromMe: false, sender: 'Helena' },
      { id: 'fa25', text: 'Noch unklar.', timestamp: daysAgo(3), fromMe: true, status: 'read' },
      { id: 'fa26', text: 'Du sagst das seit drei Wochen.', timestamp: daysAgo(3), fromMe: false, sender: 'Helena' },
      { id: 'fa27', text: 'Ich weiß.', timestamp: daysAgo(3), fromMe: true, status: 'read' },
      { id: 'fa28', text: 'Ich versuche es.', timestamp: daysAgo(3), fromMe: true, status: 'read' },
      { id: 'fa29', text: 'Das sagst du auch seit drei Wochen.', timestamp: daysAgo(3), fromMe: false, sender: 'Helena' },

      { id: 'fa30', text: 'Ich habe morgen früh den Einkauf gemacht. Brauchen wir noch etwas fürs Wochenende?', timestamp: daysAgo(1), fromMe: false, sender: 'Helena' },
      { id: 'fa31', text: 'Kaffee.', timestamp: daysAgo(1), fromMe: true, status: 'read' },
      { id: 'fa32', text: 'Das steht schon auf der Liste.', timestamp: daysAgo(1), fromMe: false, sender: 'Helena' },
      { id: 'fa33', text: 'Ich könnte theoretisch vorbeikommen und „testen", ob der Kaffeevorrat reicht.', timestamp: daysAgo(1), fromMe: false, sender: 'Markus' },
      { id: 'fa34', text: 'Das nennt man nicht testen, Markus. Das nennt man konsumieren.', timestamp: daysAgo(1), fromMe: false, sender: 'Sarah' },
      { id: 'fa35', text: 'Wissenschaftlich betrachtet ist es eine Qualitätskontrolle.', timestamp: daysAgo(1), fromMe: false, sender: 'Markus' },
      { id: 'fa36', text: 'Dann ist dein Leben eine Dauerstudie.', timestamp: daysAgo(1), fromMe: false, sender: 'Laura' },
      { id: 'fa37', text: 'Danke, ich fühle mich jetzt sehr erforscht.', timestamp: daysAgo(1), fromMe: false, sender: 'Markus' },

      { id: 'fa38', text: 'Nick hat gefragt, ob jemand mit ihm Fahrrad fährt.', timestamp: daysAgo(1), fromMe: false, sender: 'Helena' },
      { id: 'fa39', text: 'Ich kann Sonntag.', timestamp: daysAgo(1), fromMe: true, status: 'read' },
      { id: 'fa40', text: 'Ich bin wahrscheinlich auch da. Wetter soll gut werden.', timestamp: daysAgo(1), fromMe: false, sender: 'Sarah' },
      { id: 'fa41', text: 'Ich bin nur mental sportlich verfügbar.', timestamp: daysAgo(1), fromMe: false, sender: 'Laura' },
      { id: 'fa42', text: 'Ich fahre mit, aber nur wenn keine Hügel involviert sind.', timestamp: daysAgo(1), fromMe: false, sender: 'Markus' },
      { id: 'fa43', text: 'Berlin ist nicht hügelig.', timestamp: daysAgo(1), fromMe: false, sender: 'Helena' },
      { id: 'fa44', text: 'Das ist eine Frage der Perspektive.', timestamp: daysAgo(1), fromMe: false, sender: 'Markus' },

      { id: 'fa45', text: 'Ich habe den Schlüssel für die Gartenlaube gefunden. Lag in der Brotschublade.', timestamp: hoursAgo(2), fromMe: false, sender: 'Helena' },
      { id: 'fa46', text: 'Das ist ein klassischer Ort.', timestamp: hoursAgo(2), fromMe: true, status: 'read' },
      { id: 'fa47', text: 'Das ist ein Ort für Dinge, die „später wichtig werden".', timestamp: hoursAgo(2), fromMe: false, sender: 'Markus' },
      { id: 'fa48', text: 'Oder für Dinge, die man nie wieder sucht.', timestamp: hoursAgo(2), fromMe: false, sender: 'Laura' },
      { id: 'fa49', text: 'Oder für Markus’ Werkzeuge.', timestamp: hoursAgo(2), fromMe: false, sender: 'Sarah' },
      { id: 'fa50', text: 'Das war einmal ein Missverständnis.', timestamp: hoursAgo(2), fromMe: false, sender: 'Markus' },

      { id: 'fa51', text: 'Abendessen heute bei uns oder draußen?', timestamp: hoursAgo(1.5), fromMe: false, sender: 'Helena' },
      { id: 'fa52', text: 'Eher ruhig zuhause.', timestamp: hoursAgo(1.5), fromMe: true, status: 'read' },
      { id: 'fa53', text: 'Ich bringe was mit.', timestamp: hoursAgo(1.5), fromMe: false, sender: 'Sarah' },
      { id: 'fa54', text: 'Ich kann einen Salat machen, der nicht aussieht wie ein Experiment.', timestamp: hoursAgo(1.5), fromMe: false, sender: 'Laura' },
      { id: 'fa55', text: 'Ich bringe Brot. Ich kann Brot.', timestamp: hoursAgo(1.5), fromMe: false, sender: 'Markus' },
      { id: 'fa56', text: 'Das ist gut. Bitte nur Brot.', timestamp: hoursAgo(1.5), fromMe: false, sender: 'Helena' },
      { id: 'fa57', text: 'Ich fühle mich reduziert, aber akzeptiert.', timestamp: hoursAgo(1.5), fromMe: false, sender: 'Markus' },
    ],
  },
  {
    id: 'markus',
    name: 'Markus 🔧',
    avatarColor: '#0EA5E9',
    phone: '+49 30 555 0188',
    about: 'Bruder',
    lastSeen: 'online',
    unreadCount: 0,
    messages: [
      { id: 'mk1', text: 'Hast du noch dieses alte Werkzeugset aus der Garage?', timestamp: hoursAgo(3), fromMe: false },
      { id: 'mk2', text: 'Welches?', timestamp: hoursAgo(3), fromMe: true, status: 'read' },
      { id: 'mk3', text: 'Das, das immer „nur kurz" benutzt werden sollte.', timestamp: hoursAgo(3), fromMe: false },
      { id: 'mk4', text: 'Das ist sehr unspezifisch.', timestamp: hoursAgo(2.5), fromMe: true, status: 'read' },
      { id: 'mk5', text: 'Es hat mindestens eine Schraube, die du gehasst hast.', timestamp: hoursAgo(2.5), fromMe: false },
      { id: 'mk6', text: 'Das hilft nicht.', timestamp: hoursAgo(2), fromMe: true, status: 'read' },
      { id: 'mk7', text: 'Ich brauche es für ein Regal.', timestamp: hoursAgo(2), fromMe: false },
      { id: 'mk8', text: 'Du baust nie nur ein Regal.', timestamp: hoursAgo(1.5), fromMe: true, status: 'read' },
      { id: 'mk9', text: 'Das ist eine Unterstellung.', timestamp: hoursAgo(1.5), fromMe: false },
      { id: 'mk10', text: 'Eine begründete.', timestamp: hoursAgo(1), fromMe: true, status: 'read' },
      { id: 'mk11', text: 'Ich komme morgen vorbei und suche selbst.', timestamp: hoursAgo(1), fromMe: false },
      { id: 'mk12', text: 'Das ist wahrscheinlich besser.', timestamp: minutesAgo(45), fromMe: true, status: 'read' },
    ],
  },
  {
    id: 'elternchat',
    name: 'Eltern Klasse 3B 🏫',
    avatarColor: '#F59E0B',
    isGroup: true,
    about: 'Konrad-Adenauer-Schule',
    lastSeen: '',
    unreadCount: 1,
    messages: [
      { id: 'el1', text: 'Kurze Info: Sportfest nächste Woche wurde auf Donnerstag vorverlegt.', timestamp: hoursAgo(5), fromMe: false, sender: 'Frau M.' },
      { id: 'el2', text: 'Gibt es eine Regenalternative?', timestamp: hoursAgo(5), fromMe: false, sender: 'Herr K.' },
      { id: 'el3', text: 'Ja, Aula-Programm und Spiele drinnen.', timestamp: hoursAgo(5), fromMe: false, sender: 'Lehrkraft' },
      { id: 'el4', text: 'Danke für die Info!', timestamp: hoursAgo(5), fromMe: false, sender: 'Helena' },
      { id: 'el5', text: 'Weiß jemand, ob die Kinder wieder Trinkflaschen mitbringen sollen?', timestamp: hoursAgo(4.5), fromMe: false, sender: 'Frau S.' },
      { id: 'el6', text: 'Ja, bitte beschriftet.', timestamp: hoursAgo(4.5), fromMe: false, sender: 'Herr B.' },
      { id: 'el7', text: 'Ich habe letztes Mal zwei fremde Flaschen mitgebracht.', timestamp: hoursAgo(4), fromMe: false, sender: 'Helena' },
      { id: 'el8', text: 'Das passiert ständig 😄', timestamp: hoursAgo(4), fromMe: false, sender: 'Frau S.' },
      { id: 'el9', text: 'Noch eine Frage: Gibt es wieder Kuchenliste?', timestamp: hoursAgo(3.5), fromMe: false, sender: 'Herr L.' },
      { id: 'el10', text: 'Ja, hängt morgen aus.', timestamp: hoursAgo(3.5), fromMe: false, sender: 'Lehrkraft' },
      { id: 'el11', text: 'Ich übernehme gerne etwas.', timestamp: hoursAgo(3.5), fromMe: false, sender: 'Helena' },
      { id: 'el12', text: 'Ich kann beim Auf- und Abbau helfen, falls gebraucht.', timestamp: hoursAgo(3), fromMe: true, status: 'read' },
      { id: 'el13', text: 'Sehr gerne, wir melden uns!', timestamp: hoursAgo(3), fromMe: false, sender: 'Frau M.' },
    ],
  },
  {
    id: 'bmi-lage',
    name: 'BMI-S Lage / I-3 Leitung',
    avatarColor: '#1F2937',
    isGroup: true,
    about: 'Intern',
    lastSeen: '',
    unreadCount: 0,
    messages: [
      { id: 'bm1', text: 'Kurzes Update: HYDRA Version 7 ist im internen Umlauf. Änderungen aus Version 6 eingearbeitet.', timestamp: daysAgo(3), fromMe: false, sender: 'Corinna Pellner' },
      { id: 'bm2', text: 'Prüfung Punkt 4.3 diesmal stabil?', timestamp: daysAgo(3), fromMe: true, status: 'read' },
      { id: 'bm3', text: 'Ja. Formulierung ist jetzt neutralisiert, keine juristischen Angriffsflächen mehr.', timestamp: daysAgo(3), fromMe: false, sender: 'Corinna Pellner' },
      { id: 'bm4', text: 'Abt. II fragt erneut nach Lagebild Wirtschaft Süd. gleiche Anfrage wie letzte Woche.', timestamp: daysAgo(3), fromMe: false, sender: 'Lukas Stöver' },
      { id: 'bm5', text: 'Zurückstellen. Keine neuen Freigaben.', timestamp: daysAgo(3), fromMe: true, status: 'read' },
      { id: 'bm6', text: 'Presseseitig kommt eine Nachfrage zur „Verfahrensbeschleunigung HYDRA".', timestamp: daysAgo(3), fromMe: false, sender: 'Marcus Kleh' },
      { id: 'bm7', text: 'Standardantwort vorbereiten. Keine Details.', timestamp: daysAgo(3), fromMe: true, status: 'read' },

      { id: 'bm8', text: 'Foht hat Rückfrage gestellt, warum Version 7 noch nicht final signiert ist.', timestamp: daysAgo(2), fromMe: false, sender: 'Corinna Pellner' },
      { id: 'bm9', text: 'Ich zeichne heute Abend.', timestamp: daysAgo(2), fromMe: true, status: 'read' },
      { id: 'bm10', text: 'Ich weise darauf hin, dass die Revision parallel läuft.', timestamp: daysAgo(2), fromMe: false, sender: 'Corinna Pellner' },
      { id: 'bm11', text: 'Ich weiß.', timestamp: daysAgo(2), fromMe: true, status: 'read' },
      { id: 'bm12', text: 'Anruf aus Lagezentrum: verpasster Rückruf aus dem Kanzleramt-Referat.', timestamp: daysAgo(2), fromMe: false, sender: 'Lukas Stöver' },
      { id: 'bm13', text: 'Ich rufe zurück.', timestamp: daysAgo(2), fromMe: true, status: 'read' },

      { id: 'bm14', text: 'Medienanfrage „KONTEXT" eingegangen. Thema: Vergabeprozesse BMI-S.', timestamp: daysAgo(2), fromMe: false, sender: 'Marcus Kleh' },
      { id: 'bm15', text: 'Nicht bestätigen, nicht dementieren. Standardblock.', timestamp: daysAgo(2), fromMe: true, status: 'read' },
      { id: 'bm16', text: 'Das wird nicht reichen.', timestamp: daysAgo(2), fromMe: false, sender: 'Corinna Pellner' },
      { id: 'bm17', text: 'Es muss reichen.', timestamp: daysAgo(2), fromMe: true, status: 'read' },
    ],
  },
  {
    id: 'pia-netz',
    name: 'PIA-Netz (BfV-S / BND)',
    avatarColor: '#0F766E',
    isGroup: true,
    about: 'Verschlusssache',
    lastSeen: '',
    unreadCount: 0,
    messages: [
      { id: 'pi1', text: 'NORDLICHT Zielmatrix aktualisiert. Zwei Profile wurden inaktiv gesetzt.', timestamp: daysAgo(4), fromMe: false, sender: 'Vehlow' },
      { id: 'pi2', text: 'Datenlage bei Ziel 17 weiterhin inkonsistent.', timestamp: daysAgo(4), fromMe: false, sender: 'Beilschmidt' },
      { id: 'pi3', text: 'Auslandsfeed zeigt neue Verschlüsselungsstruktur. Verzögerung ca. 12h.', timestamp: daysAgo(4), fromMe: false, sender: 'Lugner' },
      { id: 'pi4', text: 'Keine strukturellen Änderungen ohne Freigabe.', timestamp: daysAgo(4), fromMe: true, status: 'read' },

      { id: 'pi5', text: 'Es gibt interne Kritik an der Dauer der Maßnahme.', timestamp: daysAgo(3.5), fromMe: false, sender: 'Vehlow' },
      { id: 'pi6', text: 'Interne Kritik ist kein operativer Faktor.', timestamp: daysAgo(3.5), fromMe: true, status: 'read' },
      { id: 'pi7', text: 'Ein parlamentarischer Mitarbeiter hat erneut Zugriff auf Teilinformationen angefragt.', timestamp: daysAgo(3.5), fromMe: false, sender: 'Beilschmidt' },
      { id: 'pi8', text: 'Ablehnen.', timestamp: daysAgo(3.5), fromMe: true, status: 'read' },

      { id: 'pi9', text: 'Hinweis: BND-Feed liefert neue Metadaten aus Beirut-Kanal.', timestamp: daysAgo(3), fromMe: false, sender: 'Lugner' },
      { id: 'pi10', text: 'In NORDLICHT aufnehmen?', timestamp: daysAgo(3), fromMe: false, sender: 'Vehlow' },
      { id: 'pi11', text: 'Nur nach Filterung.', timestamp: daysAgo(3), fromMe: true, status: 'read' },
    ],
  },
  {
    id: 'hydra-vergabe',
    name: 'HYDRA Vergabe',
    avatarColor: '#4F46E5',
    isGroup: true,
    about: 'Wirtschaftsabgleich',
    lastSeen: '',
    unreadCount: 0,
    messages: [
      { id: 'hy1', text: 'Wir benötigen Klarstellung zur angepassten Wertungsmatrix Punkt 4.3.', timestamp: daysAgo(2.5), fromMe: false, sender: 'Dr. Kahlen' },
      { id: 'hy2', text: 'Die Anpassung dient der rechtlichen Stabilität des Verfahrens.', timestamp: daysAgo(2.5), fromMe: true, status: 'read' },
      { id: 'hy3', text: 'Verstanden. Wir bitten um zeitnahe finale Bestätigung.', timestamp: daysAgo(2.5), fromMe: false, sender: 'Dr. Kahlen' },
      { id: 'hy4', text: 'Finale Version geht heute raus.', timestamp: daysAgo(2.5), fromMe: false, sender: 'Corinna Pellner' },
      { id: 'hy5', text: 'So bleibt es.', timestamp: daysAgo(2.5), fromMe: true, status: 'read' },

      { id: 'hy6', text: 'Noch eine operative Frage: Kommunikation mit ARGUS Cyberdefense läuft über Sie oder direkt?', timestamp: daysAgo(2), fromMe: false, sender: 'Dr. Kahlen' },
      { id: 'hy7', text: 'Direkt über BMI-S-Kontaktstelle.', timestamp: daysAgo(2), fromMe: true, status: 'read' },
      { id: 'hy8', text: 'Gut. Dann halten wir es formal sauber.', timestamp: daysAgo(2), fromMe: false, sender: 'Dr. Kahlen' },
    ],
  },
  {
    id: 'pressestelle',
    name: 'Pressestelle BMI-S',
    avatarColor: '#B91C1C',
    isGroup: true,
    about: 'Kommunikation',
    lastSeen: '',
    unreadCount: 0,
    messages: [
      { id: 'pr1', text: 'KONTEXT hat erneut nach einem Kommentar zur NORDLICHT-Diskussion gefragt.', timestamp: daysAgo(2), fromMe: false, sender: 'Marcus Kleh' },
      { id: 'pr2', text: 'Ich empfehle klare Trennung: operative Ebene / politische Bewertung.', timestamp: daysAgo(2), fromMe: false, sender: 'Naomi Behlau' },
      { id: 'pr3', text: 'Zu weich.', timestamp: daysAgo(2), fromMe: true, status: 'read' },
      { id: 'pr4', text: 'Dann: „Keine laufenden Verfahren werden kommentiert."', timestamp: daysAgo(2), fromMe: false, sender: 'Naomi Behlau' },
      { id: 'pr5', text: 'Das ist Standard.', timestamp: daysAgo(2), fromMe: false, sender: 'Marcus Kleh' },
      { id: 'pr6', text: 'Dann genau das.', timestamp: daysAgo(2), fromMe: true, status: 'read' },

      { id: 'pr7', text: 'Es gibt eine zusätzliche Anfrage wegen „indirekter Datenverknüpfung".', timestamp: daysAgo(1.5), fromMe: false, sender: 'Naomi Behlau' },
      { id: 'pr8', text: 'Nicht beantworten.', timestamp: daysAgo(1.5), fromMe: true, status: 'read' },
      { id: 'pr9', text: 'Verstanden.', timestamp: daysAgo(1.5), fromMe: false, sender: 'Marcus Kleh' },
    ],
  },
  {
    id: 'vorzimmer',
    name: 'Vorzimmer / Org',
    avatarColor: '#9333EA',
    isGroup: true,
    about: 'Organisation',
    lastSeen: '',
    unreadCount: 0,
    messages: [
      { id: 'vo1', text: 'Ihr 17:00 Termin mit Foht wurde vorgezogen auf 16:30.', timestamp: daysAgo(3.5), fromMe: false, sender: 'Johanna Merke' },
      { id: 'vo2', text: 'Warum?', timestamp: daysAgo(3.5), fromMe: true, status: 'read' },
      { id: 'vo3', text: 'Keine Begründung angegeben. Nur „dringend".', timestamp: daysAgo(3.5), fromMe: false, sender: 'Johanna Merke' },
      { id: 'vo4', text: 'Transport ist organisiert.', timestamp: daysAgo(3.5), fromMe: false, sender: 'Lukas Stöver' },
      { id: 'vo5', text: 'Gut.', timestamp: daysAgo(3.5), fromMe: true, status: 'read' },

      { id: 'vo6', text: 'Außerdem: Ihr Diensthandy hat heute Morgen einen verpassten Anruf aus dem Kanzleramt-Referat erhalten.', timestamp: daysAgo(3), fromMe: false, sender: 'Johanna Merke' },
      { id: 'vo7', text: 'Ich weiß.', timestamp: daysAgo(3), fromMe: true, status: 'read' },
      { id: 'vo8', text: 'Soll ich zurückstellen oder direkt verbinden?', timestamp: daysAgo(3), fromMe: false, sender: 'Johanna Merke' },
      { id: 'vo9', text: 'Direkt verbinden, sobald verfügbar.', timestamp: daysAgo(3), fromMe: true, status: 'read' },
    ],
  },
  {
    id: 'vater',
    name: 'Vater',
    avatarColor: '#1E3A8A',
    phone: '+49 331 555 0162',
    about: 'Vater, Oberst a. D. (NVS)',
    lastSeen: 'online',
    unreadCount: 1,
    messages: [
      { id: 'kl1', text: 'Hast du an Nicks Sportfest gedacht? Donnerstag.', timestamp: hoursAgo(8), fromMe: false },
      { id: 'kl2', text: 'Helena übernimmt das Organisatorische, ich komme später dazu.', timestamp: hoursAgo(8), fromMe: true, status: 'read' },
      { id: 'kl3', text: 'Margit fragt nach. Sie macht sich Sorgen wegen deiner Überstunden.', timestamp: hoursAgo(5), fromMe: false },
      { id: 'kl4', text: 'Ich weiß, Vater. Es ist gerade… viel.', timestamp: hoursAgo(5), fromMe: true, status: 'read' },
      { id: 'kl5', text: 'Das war es bei mir auch immer. Aber die Familie kommt zuerst.', timestamp: hoursAgo(4.5), fromMe: false },
      { id: 'kl6', text: 'Ich versuche es.', timestamp: hoursAgo(4.5), fromMe: true, status: 'read' },
      { id: 'kl7', text: 'Versuchen ist nicht genug. Du bist Seidt. Wir halten durch, aber wir halten zusammen.', timestamp: hoursAgo(4), fromMe: false },
      { id: 'kl8', text: 'Verstanden.', timestamp: hoursAgo(4), fromMe: true, status: 'read' },
      { id: 'kl9', text: 'Noch etwas: Sarah hat für Sonntag zugesagt. Du weißt, was das heißt.', timestamp: hoursAgo(3), fromMe: false },
      { id: 'kl10', text: 'Dass sie wieder die Lage im Land analysiert.', timestamp: hoursAgo(3), fromMe: true, status: 'read' },
      { id: 'kl11', text: 'Genau. Sei vorbereitet.', timestamp: hoursAgo(2.5), fromMe: false },
      { id: 'kl12', text: 'Bin ich. Wann seid ihr da?', timestamp: hoursAgo(2.5), fromMe: true, status: 'read' },
      { id: 'kl13', text: 'Gegen Mittag. Margit bringt Kuchen mit.', timestamp: hoursAgo(2), fromMe: false },
      { id: 'kl14', text: 'Kaffee steht bereit. Bis dann.', timestamp: hoursAgo(2), fromMe: true, status: 'read' },
      { id: 'kl15', text: 'Daniel.', timestamp: hoursAgo(2), fromMe: false },
      { id: 'kl16', text: 'Ja?', timestamp: hoursAgo(2), fromMe: true, status: 'read' },
      { id: 'kl17', text: 'Es ist gut, dass du wieder mehr zu Hause bist.', timestamp: hoursAgo(2), fromMe: false },
    ],
  },
  {
    id: 'mutter',
    name: 'Mama',
    avatarColor: '#16A34A',
    phone: '+49 331 555 0163',
    about: 'Mama, Lehrerin i. R.',
    lastSeen: 'online',
    unreadCount: 0,
    messages: [
      { id: 'ma1', text: 'Schatz, hast du Lotta ihre Ohren-Tropfen mitgegeben?', timestamp: daysAgo(1), fromMe: false },
      { id: 'ma2', text: 'Ja, liegen in der Tasche.', timestamp: daysAgo(1), fromMe: true, status: 'read' },
      { id: 'ma3', text: 'Gut. Und der Inhalator für Nick?', timestamp: daysAgo(1), fromMe: false },
      { id: 'ma4', text: 'Auch dabei.', timestamp: daysAgo(1), fromMe: true, status: 'read' },
      { id: 'ma5', text: 'Danke. Dein Vater hat wieder vom Yacht-Club erzählt, du weißt ja wie er ist.', timestamp: daysAgo(1), fromMe: false },
      { id: 'ma6', text: 'Markus kommt am Samstag?', timestamp: daysAgo(1), fromMe: true, status: 'read' },
      { id: 'ma7', text: 'Ja, und Sarah hat auch zugesagt. Es wird voll bei euch.', timestamp: daysAgo(1), fromMe: false },
      { id: 'ma8', text: 'Soll ich was mitbringen?', timestamp: daysAgo(1), fromMe: true, status: 'read' },
      { id: 'ma9', text: 'Dich. Das reicht.', timestamp: daysAgo(1), fromMe: false },
      { id: 'ma10', text: 'Hast du die Nummer von Dr. Liebig parat? Wegen Lottas Nachsorge.', timestamp: hoursAgo(6), fromMe: false },
      { id: 'ma11', text: 'Ja, ich schicke sie dir gleich.', timestamp: hoursAgo(6), fromMe: true, status: 'read' },
      { id: 'ma12', text: 'Und grüß Helena von mir. Sie klang am Telefon so müde.', timestamp: hoursAgo(5), fromMe: false },
      { id: 'ma13', text: 'Mach ich. Sie freut sich.', timestamp: hoursAgo(5), fromMe: true, status: 'read' },
      { id: 'ma14', text: 'Schlaf gut, Schatz.', timestamp: hoursAgo(4), fromMe: false },
    ],
  },
  {
    id: 'schwester-sarah',
    name: 'Sarah',
    avatarColor: '#78716C',
    phone: '+49 30 555 0190',
    about: 'Schwester, Hauptmann (NVS)',
    lastSeen: 'online',
    unreadCount: 2,
    messages: [
      { id: 'ss1', text: 'Foht-Termin verschoben?', timestamp: hoursAgo(2), fromMe: false },
      { id: 'ss2', text: 'Auf 16:30, keine Begründung.', timestamp: hoursAgo(2), fromMe: true, status: 'read' },
      { id: 'ss3', text: 'Ungewöhnlich. Aus dem BMinVtg heißt es, die Revision prüft HYDRA-Querelen.', timestamp: hoursAgo(2), fromMe: false },
      { id: 'ss4', text: 'Halte dich da raus.', timestamp: hoursAgo(2), fromMe: true, status: 'read' },
      { id: 'ss5', text: 'Ich bin Offizier, ich halte mich nirgendwo raus.', timestamp: hoursAgo(1.5), fromMe: false },
      { id: 'ss6', text: 'Sarah.', timestamp: hoursAgo(1.5), fromMe: true, status: 'read' },
      { id: 'ss7', text: 'Schon gut. Sonntag bei euch?', timestamp: hoursAgo(1), fromMe: false },
      { id: 'ss8', text: 'Ja, bring Mark mit, falls er Zeit hat.', timestamp: hoursAgo(1), fromMe: true, status: 'read' },
      { id: 'ss9', text: 'Er ist in Übung. Ich komme allein.', timestamp: minutesAgo(45), fromMe: false },
      { id: 'ss10', text: 'Alles klar. Soll ich was vorbereiten?', timestamp: minutesAgo(40), fromMe: true, status: 'read' },
      { id: 'ss11', text: 'Nein, ich bringe Brot mit. Wie immer.', timestamp: minutesAgo(35), fromMe: false },
      { id: 'ss12', text: 'Vater kommt auch. Er hat etwas auf dem Herzen.', timestamp: minutesAgo(30), fromMe: false },
    ],
  },
  {
    id: 'schwester-laura',
    name: 'Laura S.',
    avatarColor: '#8B5CF6',
    phone: '+49 341 555 0192',
    about: 'Schwester, Psychologin',
    lastSeen: 'online',
    unreadCount: 0,
    messages: [
      { id: 'sl1', text: 'Hast du einen Moment? Ich will dir was geben, kein Notfall.', timestamp: hoursAgo(12), fromMe: false },
      { id: 'sl2', text: 'Schieß los.', timestamp: hoursAgo(12), fromMe: true, status: 'read' },
      { id: 'sl3', text: 'Du klingst müde. Nicht körperlich. Systemisch.', timestamp: hoursAgo(12), fromMe: false },
      { id: 'sl4', text: 'Danke für die Diagnose, Schwesterherz.', timestamp: hoursAgo(12), fromMe: true, status: 'read' },
      { id: 'sl5', text: 'Ich bin Psychologin, das ist mein Job. Wann hast du das letzte Mal frei genommen?', timestamp: hoursAgo(12), fromMe: false },
      { id: 'sl6', text: 'Definiere frei.', timestamp: hoursAgo(12), fromMe: true, status: 'read' },
      { id: 'sl7', text: 'Definitionen, Daniel. Immer Definitionen.', timestamp: hoursAgo(11.5), fromMe: false },
      { id: 'sl8', text: 'Sonntag vielleicht. Mit den Kindern.', timestamp: hoursAgo(11.5), fromMe: true, status: 'read' },
      { id: 'sl9', text: 'Dann nimm Sonntag. Du klingst wie Vater vor der Pensionierung.', timestamp: hoursAgo(11), fromMe: false },
      { id: 'sl10', text: 'Das ist ein Argument.', timestamp: hoursAgo(11), fromMe: true, status: 'read' },
      { id: 'sl11', text: 'Es ist eine Beobachtung. Nächste Woche in Leipzig? Ich habe einen freien Tag.', timestamp: hoursAgo(10), fromMe: false },
      { id: 'sl12', text: 'Kann ich mir nicht vorstellen, du bist immer im Dienst.', timestamp: hoursAgo(10), fromMe: true, status: 'read' },
      { id: 'sl13', text: 'Auch Psychologen brauchen Pausen. Überraschung.', timestamp: hoursAgo(9), fromMe: false },
      { id: 'sl14', text: 'Gut. Ich komme. Danke.', timestamp: hoursAgo(9), fromMe: true, status: 'read' },
    ],
  },
  {
    id: 'unknown',
    name: 'Notizen',
    avatarColor: '#5A5A5A',
    isHidden: true,
    lastSeen: '',
    unreadCount: 0,
    messages: [
      { id: 'no0', text: 'Sichere Notizen – schreibe hier alles, was niemand sehen soll.', timestamp: new Date(), fromMe: false, status: 'read' },
      { id: 'no1', text: 'HYDRA Version 7 formal sauber, inhaltlich zu glatt → Risiko der Nachverfolgung steigt', timestamp: daysAgo(5), fromMe: true, status: 'read' },
      { id: 'no2', text: 'Foht beschleunigt Prozess → unklar warum jetzt', timestamp: daysAgo(5), fromMe: true, status: 'read' },
      { id: 'no3', text: 'Pellner stabil, aber vorsichtig in Formulierungen', timestamp: daysAgo(4), fromMe: true, status: 'read' },
      { id: 'no4', text: 'NORDLICHT beginnt sich politisch zu verselbstständigen (nicht mehr rein operativ)', timestamp: daysAgo(4), fromMe: true, status: 'read', clueId: 'wazaaah:nordlicht' },
      { id: 'no5', text: 'Presselage kontrollierbar, solange keine Leaks aus Wirtschaft kommen', timestamp: daysAgo(3), fromMe: true, status: 'read' },
      { id: 'no6', text: 'Telefonanrufe Kanzleramt-Referat → Zusammenhang mit Revision prüfen', timestamp: daysAgo(3), fromMe: true, status: 'read' },
      { id: 'no7', text: 'Kalender: keine offenen Fenster zwischen 15–18 Uhr nächste Woche', timestamp: daysAgo(2), fromMe: true, status: 'read' },
      { id: 'no8', text: 'Sonntag: feste Familienzeit einhalten', timestamp: daysAgo(2), fromMe: true, status: 'read' },
      { id: 'no9', text: 'Kaffee nachkaufen (Helena hat es bereits auf Liste)', timestamp: daysAgo(1), fromMe: true, status: 'read' },
      { id: 'no10', text: 'Fahrradkette von Nick prüfen lassen', timestamp: daysAgo(1), fromMe: true, status: 'read' },
      { id: 'no11', text: 'Markus nicht allein in Garage lassen (Werkzeuge verschwinden sonst „in Projekten")', timestamp: daysAgo(1), fromMe: true, status: 'read' },
      { id: 'no12', text: 'Laura: einmal aktiv anrufen, nicht nur reagieren', timestamp: hoursAgo(12), fromMe: true, status: 'read' },
      { id: 'no13', text: 'Helena: Urlaubsgespräch nicht wieder verschieben', timestamp: hoursAgo(8), fromMe: true, status: 'read' },
      { id: 'no14', text: 'Schlaf: aktuell zu wenig, Konzentration sinkt am Nachmittag', timestamp: hoursAgo(4), fromMe: true, status: 'read' },
      { id: 'no15', text: 'Kalender: weniger Abendtermine, mehr Pufferzeiten', timestamp: hoursAgo(2), fromMe: true, status: 'read' },
    ],
  },
];

export const getChatById = (id: string): Chat | undefined =>
  initialChats.find((c) => c.id === id);
