export const COLORS = {
  bg: '#fff',
  text: '#262626',
  muted: '#8e8e8e',
  border: '#efefef',
  accent: '#ed4956',
  igGradient: 'linear-gradient(45deg, #f09433 0%, #e6683c 25%, #dc2743 50%, #cc2366 75%, #bc1888 100%)',
};

export type Msg = { id: number; fromMe: boolean; text: string; time: string };
export type Chat = {
  id: number;
  user: string;
  avatar: string;
  img: string | null;
  online: boolean;
  unread: number;
  messages: Msg[];
};

export const CHATS: Chat[] = [
  {
    id: 1,
    user: 'helena_seidt',
    avatar: '❤️',
    img: 'https://picsum.photos/seed/lumi1/800/800',
    online: true,
    unread: 1,
    messages: [
      { id: 1, fromMe: false, text: 'Guten Morgen ❤️ Schon im Büro?', time: '07:12' },
      { id: 2, fromMe: true, text: 'Ja, seit kurz nach sieben.', time: '07:14' },
      { id: 3, fromMe: false, text: 'Hast du gut geschlafen?', time: '07:15' },
      { id: 4, fromMe: true, text: 'Ging so. War gestern einfach spät.', time: '07:16' },
      { id: 5, fromMe: false, text: 'Das habe ich gemerkt. Du warst ungewöhnlich still.', time: '07:17' },
      { id: 6, fromMe: true, text: 'Nur viel im Kopf.', time: '07:18' },
      { id: 7, fromMe: false, text: 'Ich hoffe, nichts Ernstes.', time: '07:19' },
      { id: 8, fromMe: true, text: 'Nein, nur Arbeit.', time: '07:20' },
      { id: 9, fromMe: false, text: 'Versprich mir, dass du heute nicht wieder bis 22 Uhr bleibst.', time: '07:22' },
      { id: 10, fromMe: true, text: 'Ich versuche es.', time: '07:25' },
      { id: 11, fromMe: false, text: '"Ich versuche es" heißt meistens "Nein". 😄', time: '07:26' },
      { id: 12, fromMe: true, text: 'Diesmal wirklich.', time: '07:28' },
      { id: 13, fromMe: false, text: 'Nick braucht morgen Sportsachen. Kannst du die heute Abend schon ins Auto legen?', time: '07:30' },
      { id: 14, fromMe: true, text: 'Sind bereits im Kofferraum.', time: '07:32' },
      { id: 15, fromMe: false, text: 'Perfekt.', time: '07:33' },
      { id: 16, fromMe: false, text: 'Lotta möchte morgen unbedingt ihren neuen Rucksack mitnehmen.', time: '07:35' },
      { id: 17, fromMe: true, text: 'Den mit den Katzen?', time: '07:36' },
      { id: 18, fromMe: false, text: 'Natürlich den mit den Katzen. 😅', time: '07:37' },
      { id: 19, fromMe: true, text: 'Dann wird Aspirin wohl Konkurrenz bekommen.', time: '07:38' },
      { id: 20, fromMe: false, text: '😂', time: '07:38' },
      { id: 21, fromMe: false, text: 'Apropos … hat Aspirin heute Morgen wieder versucht, auf den Küchenschrank zu springen?', time: '07:40' },
      { id: 22, fromMe: true, text: 'Ja.', time: '07:42' },
      { id: 23, fromMe: false, text: 'Hat er es geschafft?', time: '07:42' },
      { id: 24, fromMe: true, text: 'Leider.', time: '07:43' },
      { id: 25, fromMe: false, text: 'Ich wusste es.', time: '07:43' },
      { id: 26, fromMe: true, text: 'Linie 7 hat ihn dabei beobachtet wie eine Königin.', time: '07:45' },
      { id: 27, fromMe: false, text: 'Unsere Katzen haben eindeutig zu viel Selbstbewusstsein.', time: '07:46' },
      { id: 28, fromMe: true, text: 'Von wem sie das wohl haben? 😉', time: '07:47' },
      { id: 29, fromMe: false, text: 'Sehr witzig.', time: '07:48' },
      { id: 30, fromMe: false, text: '❤️ Helena hat deine Nachricht mit einem Herz markiert.', time: '07:48' },
      { id: 31, fromMe: false, text: 'Denkst du bitte an Brot?', time: '17:30' },
      { id: 32, fromMe: true, text: 'Ja.', time: '17:32' },
      { id: 33, fromMe: false, text: 'Milch?', time: '17:33' },
      { id: 34, fromMe: true, text: 'Ja.', time: '17:33' },
      { id: 35, fromMe: false, text: 'Eier?', time: '17:33' },
      { id: 36, fromMe: true, text: 'Ja.', time: '17:34' },
      { id: 37, fromMe: false, text: 'Butter?', time: '17:34' },
      { id: 38, fromMe: true, text: 'Ich mache einfach ein Bild vom Einkaufszettel.', time: '17:35' },
      { id: 39, fromMe: false, text: 'Das wäre wahrscheinlich einfacher. 😂', time: '17:36' },
      { id: 40, fromMe: false, text: '[Bild]', time: '17:36' },
      { id: 41, fromMe: true, text: 'Erledigt.', time: '18:20' },
      { id: 42, fromMe: false, text: 'Wo bist du?', time: '20:41' },
      { id: 43, fromMe: true, text: 'Gerade los.', time: '20:42' },
      { id: 44, fromMe: false, text: 'Alles okay?', time: '20:42' },
      { id: 45, fromMe: true, text: 'Ja.', time: '20:42' },
      { id: 46, fromMe: false, text: 'Die Kinder fragen schon nach dir.', time: '20:43' },
      { id: 47, fromMe: true, text: 'Bin in ungefähr 30 Minuten da.', time: '20:44' },
      { id: 48, fromMe: false, text: 'Wir warten mit dem Nachtisch.', time: '20:45' },
      { id: 49, fromMe: true, text: '❤️', time: '20:45' },
    ],
  },
  {
    id: 2,
    user: 'markus_seidt',
    avatar: '⛵',
    img: 'https://picsum.photos/seed/lumi2/800/800',
    online: true,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Moin.', time: '09:01' },
      { id: 2, fromMe: true, text: 'Morgen.', time: '09:02' },
      { id: 3, fromMe: false, text: 'Samstag Segeln?', time: '09:02' },
      { id: 4, fromMe: true, text: 'Sieht gut aus.', time: '09:04' },
      { id: 5, fromMe: false, text: 'Wetterbericht sagt Windstärke 3 bis 4.', time: '09:05' },
      { id: 6, fromMe: true, text: 'Perfekt.', time: '09:06' },
      { id: 7, fromMe: false, text: 'Sturm & Ordnung freut sich.', time: '09:07' },
      { id: 8, fromMe: true, text: 'Hoffentlich diesmal ohne Motorprobleme.', time: '09:08' },
      { id: 9, fromMe: false, text: 'Die sind behoben.', time: '09:09' },
      { id: 10, fromMe: true, text: 'Das hast du letzztes Mal auch gesagt.', time: '09:10' },
      { id: 11, fromMe: false, text: 'Diesmal wirklich. 😄', time: '09:11' },
      { id: 12, fromMe: true, text: 'Wann treffen?', time: '09:12' },
      { id: 13, fromMe: false, text: '09:30 Uhr am Steg.', time: '09:13' },
      { id: 14, fromMe: true, text: 'Passt.', time: '09:14' },
      { id: 15, fromMe: false, text: 'Papa kommt vielleicht vorbei.', time: '09:15' },
      { id: 16, fromMe: true, text: 'Gerne.', time: '09:16' },
      { id: 17, fromMe: false, text: 'Bring Sonnencreme mit.', time: '09:17' },
      { id: 18, fromMe: true, text: 'Mach ich.', time: '09:18' },
    ],
  },
  {
    id: 3,
    user: 'max_reusser',
    avatar: '🏃',
    img: 'https://picsum.photos/seed/lumi3/800/800',
    online: false,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Laufen morgen?', time: '20:15' },
      { id: 2, fromMe: true, text: 'Klar.', time: '20:16' },
      { id: 3, fromMe: false, text: '06:30 Uhr.', time: '20:16' },
      { id: 4, fromMe: true, text: 'Wie immer.', time: '20:17' },
      { id: 5, fromMe: false, text: '10 Kilometer?', time: '20:17' },
      { id: 6, fromMe: true, text: 'Ja.', time: '20:18' },
      { id: 7, fromMe: false, text: 'Nicht wieder so schnell loslaufen.', time: '20:19' },
      { id: 8, fromMe: true, text: 'Du bist doch derjenige, der immer sprintet.', time: '20:20' },
      { id: 9, fromMe: false, text: 'Das ist Motivation.', time: '20:21' },
      { id: 10, fromMe: true, text: 'Das ist Wahnsinn.', time: '20:22' },
      { id: 11, fromMe: false, text: '❤️ Max hat deine Nachricht mit einem Herz markiert.', time: '20:22' },
      { id: 12, fromMe: false, text: 'Danach Kaffee?', time: '20:25' },
      { id: 13, fromMe: true, text: 'Auf jeden Fall.', time: '20:26' },
      { id: 14, fromMe: false, text: 'Dasselbe Café?', time: '20:27' },
      { id: 15, fromMe: true, text: 'Ja.', time: '20:28' },
      { id: 16, fromMe: false, text: 'Deal.', time: '20:29' },
    ],
  },
  {
    id: 4,
    user: 'sarah_seidt',
    avatar: '🎖️',
    img: 'https://picsum.photos/seed/lumi4/800/800',
    online: false,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Herzlichen Glückwunsch nochmal zum Vortrag.', time: '18:30' },
      { id: 2, fromMe: true, text: 'Danke dir.', time: '18:32' },
      { id: 3, fromMe: false, text: 'Vater war erstaunlich begeistert.', time: '18:33' },
      { id: 4, fromMe: true, text: 'Hat er tatsächlich etwas gesagt?', time: '18:34' },
      { id: 5, fromMe: false, text: 'Mehr Lob bekommst du von ihm kaum.', time: '18:36' },
      { id: 6, fromMe: true, text: 'Dann nehme ich das als Kompliment.', time: '18:37' },
      { id: 7, fromMe: false, text: 'Wie geht\'s Helena?', time: '18:40' },
      { id: 8, fromMe: true, text: 'Gut. Viel Arbeit.', time: '18:42' },
      { id: 9, fromMe: false, text: 'Grüße sie bitte.', time: '18:43' },
      { id: 10, fromMe: true, text: 'Mache ich.', time: '18:44' },
    ],
  },
  {
    id: 5,
    user: 'laura_seidt',
    avatar: '📚',
    img: 'https://picsum.photos/seed/lumi5/800/800',
    online: false,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Hast du das Buch inzwischen fertig gelesen?', time: '15:10' },
      { id: 2, fromMe: true, text: 'Noch nicht.', time: '15:12' },
      { id: 3, fromMe: false, text: 'Kapitel 7 fand ich besonders spannend.', time: '15:13' },
      { id: 4, fromMe: true, text: 'Bin gerade dort.', time: '15:14' },
      { id: 5, fromMe: false, text: 'Dann verrate ich nichts. 😄', time: '15:15' },
      { id: 6, fromMe: true, text: 'Danke.', time: '15:16' },
      { id: 7, fromMe: false, text: 'Wann sehen wir uns?', time: '15:18' },
      { id: 8, fromMe: true, text: 'Wahrscheinlich bei Mama am Sonntag.', time: '15:20' },
      { id: 9, fromMe: false, text: 'Perfekt.', time: '15:21' },
    ],
  },
  {
    id: 6,
    user: 'tobias_brauer',
    avatar: '⚖️',
    img: 'https://picsum.photos/seed/lumi6/800/800',
    online: true,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Grillen nächsten Sonntag?', time: '11:00' },
      { id: 2, fromMe: true, text: 'Wir sind dabei.', time: '11:02' },
      { id: 3, fromMe: false, text: 'Die Kinder freuen sich schon.', time: '11:03' },
      { id: 4, fromMe: true, text: 'Unsere auch.', time: '11:04' },
      { id: 5, fromMe: false, text: 'Bringst du wieder den Kartoffelsalat mit?', time: '11:05' },
      { id: 6, fromMe: true, text: 'Helena macht ihn.', time: '11:06' },
      { id: 7, fromMe: false, text: 'Perfekt.', time: '11:07' },
      { id: 8, fromMe: true, text: 'Soll ich noch etwas mitbringen?', time: '11:08' },
      { id: 9, fromMe: false, text: 'Nur gute Laune.', time: '11:10' },
      { id: 10, fromMe: true, text: 'Das bekomme ich hin.', time: '11:11' },
      { id: 11, fromMe: false, text: 'Helena meinte, du interessierst dich wieder fürs Segeln.', time: '19:00' },
      { id: 12, fromMe: true, text: 'Markus hat mich überredet.', time: '19:02' },
      { id: 13, fromMe: false, text: 'Gute Entscheidung.', time: '19:03' },
      { id: 14, fromMe: true, text: 'Wie läuft die Kanzlei?', time: '19:05' },
      { id: 15, fromMe: false, text: 'Viel Arbeit, aber alles im grünen Bereich.', time: '19:07' },
      { id: 16, fromMe: true, text: 'Freut mich.', time: '19:08' },
      { id: 17, fromMe: false, text: 'Kommt ihr Samstag zum Grillen?', time: '19:10' },
      { id: 18, fromMe: true, text: 'Ja.', time: '19:11' },
    ],
  },
  {
    id: 7,
    user: 'dr_henkel',
    avatar: '🩺',
    img: 'https://picsum.photos/seed/lumi7/800/800',
    online: false,
    unread: 1,
    messages: [
      { id: 1, fromMe: false, text: 'Guten Tag, Herr Seidt.', time: '10:15' },
      { id: 2, fromMe: true, text: 'Guten Tag.', time: '10:18' },
      { id: 3, fromMe: false, text: 'Für Aspirin wäre kommende Woche die jährliche Kontrolle fällig.', time: '10:20' },
      { id: 4, fromMe: true, text: 'Mittwoch möglich?', time: '10:22' },
      { id: 5, fromMe: false, text: '16:00 Uhr wäre frei.', time: '10:25' },
      { id: 6, fromMe: true, text: 'Nehme ich.', time: '10:26' },
      { id: 7, fromMe: false, text: 'Außerdem würde ich Linie 7 ebenfalls kurz ansehen.', time: '10:28' },
      { id: 8, fromMe: true, text: 'Kein Problem.', time: '10:29' },
      { id: 9, fromMe: false, text: 'Bis Mittwoch.', time: '10:30' },
      { id: 10, fromMe: true, text: 'Vielen Dank.', time: '10:31' },
      { id: 11, fromMe: false, text: 'Hallo Herr Seidt.', time: 'GESTERN' },
      { id: 12, fromMe: true, text: 'Hallo Frau Doktor.', time: 'GESTERN' },
      { id: 13, fromMe: false, text: 'Aspirin hat heute einen Preis gewonnen?', time: 'GESTERN' },
      { id: 14, fromMe: true, text: 'Best in Variety. 😄', time: 'GESTERN' },
      { id: 15, fromMe: false, text: 'Herzlichen Glückwunsch!', time: 'GESTERN' },
      { id: 16, fromMe: true, text: 'Danke.', time: 'GESTERN' },
      { id: 17, fromMe: false, text: 'Linie 7 entwickelt sich ebenfalls hervorragend.', time: 'GESTERN' },
      { id: 18, fromMe: true, text: 'Das hören wir gern.', time: 'GESTERN' },
    ],
  },
  {
    id: 8,
    user: 'nick_seidt',
    avatar: '⚽',
    img: 'https://picsum.photos/seed/lumi8/800/800',
    online: true,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Papaaa 😄⚽', time: '17:30' },
      { id: 2, fromMe: false, text: '[Bild]', time: '17:30' },
      { id: 3, fromMe: true, text: 'Stark!', time: '17:33' },
      { id: 4, fromMe: false, text: 'Ich hab heute 2 Tore gemacht!!', time: '17:34' },
      { id: 5, fromMe: true, text: 'Das ist richtig gut.', time: '17:35' },
      { id: 6, fromMe: false, text: 'Der Trainer hat gesagt ich soll mehr schießen.', time: '17:36' },
      { id: 7, fromMe: true, text: 'Hat er recht.', time: '17:37' },
      { id: 8, fromMe: false, text: 'Kommst du Samstag zugucken?', time: '17:38' },
      { id: 9, fromMe: true, text: 'Natürlich.', time: '17:39' },
      { id: 10, fromMe: false, text: 'Versprochen?', time: '17:39' },
      { id: 11, fromMe: true, text: 'Versprochen.', time: '17:40' },
      { id: 12, fromMe: false, text: '❤️ Nick hat deine Nachricht mit einem Herz markiert.', time: '17:40' },
      { id: 13, fromMe: false, text: 'Danach Pizza?', time: '17:42' },
      { id: 14, fromMe: true, text: 'Nach zwei Toren hast du sie dir verdient.', time: '17:43' },
      { id: 15, fromMe: false, text: 'JAAAAAA 🍕', time: '17:43' },
    ],
  },
  {
    id: 9,
    user: 'sabine_wernecke',
    avatar: '🏛️',
    img: 'https://picsum.photos/seed/lumi9/800/800',
    online: false,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Guten Morgen, Herr Seidt.', time: '08:30' },
      { id: 2, fromMe: true, text: 'Guten Morgen, Frau Wernecke.', time: '08:32' },
      { id: 3, fromMe: false, text: 'Haben Sie am Freitag Zeit für den Empfang im Rathaus Babelsberg?', time: '08:33' },
      { id: 4, fromMe: true, text: 'Ab 18 Uhr sollte es passen.', time: '08:36' },
      { id: 5, fromMe: false, text: 'Wunderbar. Ich habe Sie auf die Gästeliste gesetzt.', time: '08:38' },
      { id: 6, fromMe: true, text: 'Vielen Dank.', time: '08:40' },
      { id: 7, fromMe: false, text: 'Könnten Sie ein paar Worte zur Stadtsanierung sagen?', time: '08:41' },
      { id: 8, fromMe: true, text: 'Fünf Minuten sind kein Problem.', time: '08:43' },
      { id: 9, fromMe: false, text: 'Mehr brauche ich gar nicht. 😊', time: '08:44' },
    ],
  },
  {
    id: 10,
    user: 'bernhard_kroll',
    avatar: '🎖️',
    img: 'https://picsum.photos/seed/lumi10/800/800',
    online: false,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Daniel!', time: '14:00' },
      { id: 2, fromMe: true, text: 'Herr Oberst. Wie geht es Ihnen?', time: '14:02' },
      { id: 3, fromMe: false, text: 'Sehr gut. Dein Vater hat erzählt, dass wir uns lange nicht gesehen haben.', time: '14:04' },
      { id: 4, fromMe: true, text: 'Stimmt leider.', time: '14:05' },
      { id: 5, fromMe: false, text: 'Komm doch nächste Woche auf einen Kaffee in die General-Steinhoff-Kaserne.', time: '14:07' },
      { id: 6, fromMe: true, text: 'Gerne.', time: '14:08' },
      { id: 7, fromMe: false, text: 'Ich lasse dich am Tor anmelden.', time: '14:10' },
      { id: 8, fromMe: true, text: 'Danke.', time: '14:11' },
    ],
  },
  {
    id: 11,
    user: 'dr_born',
    avatar: '🩺',
    img: 'https://picsum.photos/seed/lumi11/800/800',
    online: false,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Guten Tag, Herr Seidt.', time: '11:00' },
      { id: 2, fromMe: true, text: 'Guten Tag.', time: '11:03' },
      { id: 3, fromMe: false, text: 'Ihre Blutwerte sind unauffällig.', time: '11:05' },
      { id: 4, fromMe: true, text: 'Das freut mich.', time: '11:06' },
      { id: 5, fromMe: false, text: 'Nur etwas mehr Schlaf würde ich empfehlen.', time: '11:08' },
      { id: 6, fromMe: true, text: 'Daran arbeite ich.', time: '11:10' },
      { id: 7, fromMe: false, text: 'Das sagen Sie jedes Jahr. 😄', time: '11:11' },
      { id: 8, fromMe: true, text: 'Da haben Sie wohl recht.', time: '11:13' },
    ],
  },
  {
    id: 12,
    user: 'fahrer_schule',
    avatar: '🏫',
    img: 'https://picsum.photos/seed/lumi12/800/800',
    online: false,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Guten Abend, Herr Seidt.', time: '19:00' },
      { id: 2, fromMe: true, text: 'Guten Abend.', time: '19:02' },
      { id: 3, fromMe: false, text: 'Nick hat heute eine sehr gute Präsentation gehalten.', time: '19:04' },
      { id: 4, fromMe: true, text: 'Das freut mich sehr.', time: '19:05' },
      { id: 5, fromMe: false, text: 'Er war hervorragend vorbereitet.', time: '19:07' },
      { id: 6, fromMe: true, text: 'Vielen Dank für die Rückmeldung.', time: '19:08' },
      { id: 7, fromMe: false, text: 'Das gebe ich bei guten Leistungen immer gern weiter.', time: '19:10' },
    ],
  },
  {
    id: 13,
    user: 'prof_merker',
    avatar: '🎓',
    img: 'https://picsum.photos/seed/lumi13/800/800',
    online: false,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Guten Morgen.', time: '08:00' },
      { id: 2, fromMe: true, text: 'Guten Morgen, Herr Professor.', time: '08:03' },
      { id: 3, fromMe: false, text: 'Haben Sie bereits über einen Titel für Ihre Dissertation nachgedacht?', time: '08:05' },
      { id: 4, fromMe: true, text: 'Einige Ideen, aber noch nichts Endgültiges.', time: '08:08' },
      { id: 5, fromMe: false, text: 'Wir sollten uns Zeit dafür nehmen.', time: '08:10' },
      { id: 6, fromMe: true, text: 'Gerne nächste Woche.', time: '08:12' },
      { id: 7, fromMe: false, text: 'Dienstag um 15 Uhr?', time: '08:14' },
      { id: 8, fromMe: true, text: 'Perfekt.', time: '08:15' },
    ],
  },
  {
    id: 14,
    user: 'hwkortner',
    avatar: '👔',
    img: 'https://picsum.photos/seed/lumi14/800/800',
    online: false,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Daniel, lange nichts gehört.', time: '16:00' },
      { id: 2, fromMe: true, text: 'Das stimmt.', time: '16:03' },
      { id: 3, fromMe: false, text: 'Wie geht es der Familie?', time: '16:05' },
      { id: 4, fromMe: true, text: 'Allen gut.', time: '16:07' },
      { id: 5, fromMe: false, text: 'Das freut mich.', time: '16:08' },
      { id: 6, fromMe: true, text: 'Und Ihnen?', time: '16:10' },
      { id: 7, fromMe: false, text: 'Ich genieße inzwischen den Ruhestand deutlich mehr als erwartet.', time: '16:13' },
      { id: 8, fromMe: true, text: 'Das haben Sie sich verdient.', time: '16:15' },
    ],
  },
  {
    id: 15,
    user: 'fritz_hollwege',
    avatar: '☕',
    img: 'https://picsum.photos/seed/lumi15/800/800',
    online: false,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Denk daran, Karriere ist ein Marathon.', time: '12:00' },
      { id: 2, fromMe: true, text: 'Das werde ich nicht vergessen.', time: '12:03' },
      { id: 3, fromMe: false, text: 'Manchmal hilft Geduld mehr als Tempo.', time: '12:05' },
      { id: 4, fromMe: true, text: 'Danke für den Rat.', time: '12:07' },
      { id: 5, fromMe: false, text: 'Wir trinken bald mal wieder einen Kaffee.', time: '12:09' },
      { id: 6, fromMe: true, text: 'Sehr gern.', time: '12:10' },
    ],
  },
  {
    id: 16,
    user: 'moellmann',
    avatar: '📋',
    img: 'https://picsum.photos/seed/lumi16/800/800',
    online: false,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Guten Morgen.', time: '07:30' },
      { id: 2, fromMe: true, text: 'Guten Morgen.', time: '07:32' },
      { id: 3, fromMe: false, text: 'Sind die Unterlagen für Montag vollständig?', time: '07:34' },
      { id: 4, fromMe: true, text: 'Ja, alles vorbereitet.', time: '07:36' },
      { id: 5, fromMe: false, text: 'Hervorragend.', time: '07:37' },
      { id: 6, fromMe: true, text: 'Ich schicke Ihnen nachher noch die aktualisierte Übersicht.', time: '07:39' },
      { id: 7, fromMe: false, text: 'Vielen Dank.', time: '07:40' },
    ],
  },
  {
    id: 17,
    user: 'bernd_gerlach',
    avatar: '🗂️',
    img: 'https://picsum.photos/seed/lumi17/800/800',
    online: false,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Erinnerst du dich noch an deine erste Woche hier? 😄', time: '13:00' },
      { id: 2, fromMe: true, text: 'Leider viel zu gut.', time: '13:03' },
      { id: 3, fromMe: false, text: 'Du hast damals den Kopierer außer Betrieb gesetzt.', time: '13:05' },
      { id: 4, fromMe: true, text: 'Das muss wirklich nicht jedes Jahr erwähnt werden.', time: '13:07' },
      { id: 5, fromMe: false, text: 'Tradition ist Tradition.', time: '13:09' },
      { id: 6, fromMe: true, text: '😂', time: '13:10' },
    ],
  },
  {
    id: 18,
    user: 'dr_langguth',
    avatar: '🏃‍♂️',
    img: 'https://picsum.photos/seed/lumi18/800/800',
    online: false,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Herr Seidt, wie läuft das Training?', time: '15:00' },
      { id: 2, fromMe: true, text: 'Drei Läufe pro Woche.', time: '15:03' },
      { id: 3, fromMe: false, text: 'Knie weiterhin beschwerdefrei?', time: '15:05' },
      { id: 4, fromMe: true, text: 'Ja.', time: '15:06' },
      { id: 5, fromMe: false, text: 'Sehr gut. Behalten Sie das Pensum bei.', time: '15:08' },
      { id: 6, fromMe: true, text: 'Wird gemacht.', time: '15:10' },
    ],
  },
  {
    id: 19,
    user: 'dr_liebig',
    avatar: '👂',
    img: 'https://picsum.photos/seed/lumi19/800/800',
    online: false,
    unread: 0,
    messages: [
      { id: 1, fromMe: false, text: 'Guten Abend.', time: '18:00' },
      { id: 2, fromMe: true, text: 'Guten Abend.', time: '18:02' },
      { id: 3, fromMe: false, text: 'Lotta benötigt in sechs Monaten eine Kontrolluntersuchung.', time: '18:04' },
      { id: 4, fromMe: true, text: 'Vielen Dank für die Erinnerung.', time: '18:06' },
      { id: 5, fromMe: false, text: 'Ich reserviere Ihnen gern einen Termin.', time: '18:08' },
      { id: 6, fromMe: true, text: 'Sehr gern.', time: '18:09' },
    ],
  },
  {
    id: 20,
    user: 'aspirin_vds',
    avatar: '🐈',
    img: 'https://picsum.photos/seed/lumi20/800/800',
    online: true,
    unread: 1,
    messages: [
      { id: 1, fromMe: false, text: 'Helena: 😂', time: '21:00' },
      { id: 2, fromMe: false, text: '[Bild]', time: '21:00' },
      { id: 3, fromMe: true, text: 'Er denkt wirklich, das gehört ihm.', time: '21:02' },
      { id: 4, fromMe: false, text: 'Nick: Er wollte trinken.', time: '21:03' },
      { id: 5, fromMe: false, text: 'Lotta: Er ist süß ❤️', time: '21:04' },
      { id: 6, fromMe: false, text: 'Helena: Er hat gerade den Badezimmerteppich geklaut.', time: '21:06' },
      { id: 7, fromMe: true, text: 'Typisch Aspirin.', time: '21:07' },
      { id: 8, fromMe: false, text: 'Nick: 😂😂😂', time: '21:08' },
    ],
  },
];

export const SAMPLE_INCOMING = [
  'Hast du kurz Zeit?',
  'Schau dir das mal an...',
  'Bist du heute Abend daheim?',
  'Ich hab noch eine Frage zum Protokoll.',
  'Wir haben uns lange nicht unterhalten.',
  'LOL 😂',
  'Wo bist du gerade?',
  'Rate mal, wen ich getroffen habe!',
  'Komm schnell!',
  'Wann starten wir die Regatta?',
  'Heute Philharmoniker im Livestream 🎻',
  'Linie 7 hat wieder gespielt 😻',
  'Bist du schon an der Panke gelaufen?',
];

export const POSTS = [
  {
    id: 1,
    user: 'daniel_seidt',
    avatar: '🐱',
    avatarImg: 'https://cdn.hackclub.com/019f52cf-4135-766e-9b1f-9a35103a8644/codebrecher-6a9c130c.webp',
    img: 'https://picsum.photos/seed/lumi21/800/800',
    caption: 'Aspirin hat schon wieder meinen Sessel besetzt. Er tut so, als ob er der Chef im Haus ist... 😼🛋️ #bkh #katzenleben #potsdam',
    likes: 1337,
    time: 'VOR 2 STUNDEN',
  },
  {
    id: 2,
    user: 'cooper_retriever',
    avatar: '🐶',
    avatarImg: 'https://cdn.hackclub.com/019f52cf-56a1-785d-bed3-7ece540c0579/codebrecher-db8cd6cf.webp',
    img: 'https://picsum.photos/seed/lumi22/800/800',
    caption: 'Sonntagsrunde durch den Park Babelsberg. Bei dem Wetter macht das Toben doppelt Spaß! 🐾🌳 #doglife #potsdamdog #cooper',
    likes: 842,
    time: 'VOR 5 STUNDEN',
  },
  {
    id: 3,
    user: 'berlin_coder',
    avatar: '💻',
    avatarImg: 'https://cdn.hackclub.com/019f52cf-62a4-7231-9957-0708c2526795/codebrecher-e0501b7b.webp',
    img: 'https://picsum.photos/seed/lumi23/800/800',
    caption: 'Fehlersuche am späten Abend. Wenn das System läuft und alle Tests grün sind, schläft es sich gleich besser! ☕💻 #codinglife #cleanbuild #developer',
    likes: 2150,
    time: 'GESTERN',
  },
  {
    id: 4,
    user: 'daniel_seidt',
    avatar: '🐱',
    avatarImg: 'https://cdn.hackclub.com/019f52cf-4135-766e-9b1f-9a35103a8644/codebrecher-6a9c130c.webp',
    img: 'https://picsum.photos/seed/lumi24/800/800',
    caption: 'Aspirin hat heute in Leipzig den CAC geholt! 🏆 Black-Silver-Tabby, einfach Klasse. #bkh #katzenausstellung',
    likes: 2341,
    time: 'VOR 1 TAG',
  },
  {
    id: 5,
    user: 'daniel_seidt',
    avatar: '🐱',
    avatarImg: 'https://cdn.hackclub.com/019f52cf-4135-766e-9b1f-9a35103a8644/codebrecher-6a9c130c.webp',
    img: 'https://picsum.photos/seed/lumi25/800/800',
    caption: 'Mit "Sturm & Ordnung" raus auf die Havel. 🌬️⛵ Segeltag mit Markus. #potsdameryachtclub #segelfreunde',
    likes: 1879,
    time: 'VOR 2 TAGEN',
  },
  {
    id: 6,
    user: 'daniel_seidt',
    avatar: '🐱',
    avatarImg: 'https://cdn.hackclub.com/019f52cf-4135-766e-9b1f-9a35103a8644/codebrecher-6a9c130c.webp',
    img: 'https://picsum.photos/seed/lumi26/800/800',
    caption: 'Grieg im Nikolaisaal. Der Sitzplatz-Paten-Effekt wirkt. 🎻 #nikolaisaal #berlinerphilharmoniker',
    likes: 944,
    time: 'VOR 3 TAGEN',
  },
  {
    id: 7,
    user: 'daniel_seidt',
    avatar: '🐱',
    avatarImg: 'https://cdn.hackclub.com/019f52cf-4135-766e-9b1f-9a35103a8644/codebrecher-6a9c130c.webp',
    img: 'https://picsum.photos/seed/lumi27/800/800',
    caption: 'Sonntagsausflug in den Park Babelsberg. ☀️🌿 #parkbabelsberg #potsdam',
    likes: 1612,
    time: 'VOR 4 TAGEN',
  },
  {
    id: 8,
    user: 'daniel_seidt',
    avatar: '🐱',
    avatarImg: 'https://cdn.hackclub.com/019f52cf-4135-766e-9b1f-9a35103a8644/codebrecher-6a9c130c.webp',
    img: 'https://picsum.photos/seed/lumi28/800/800',
    caption: 'Linie 7 mit Wurf C (Februar). Fünf kleine Rabauken, alle gesund und munter. 😻 #bkh #zucht #vonderSchönhauser',
    likes: 3580,
    time: 'VOR 1 WOCHE',
  },
];

export const REELS = [
  { id: 1, user: 'daniel_seidt', avatar: '🐱', bg: 'linear-gradient(180deg, #ff9966 0%, #ff5e62 100%)', img: 'https://picsum.photos/seed/lumi29/800/800', caption: 'Aspirin jagt mal wieder dem Laserpointer hinterher. Er gibt einfach nicht auf! 🐈💨 #bkh #katzenliebe #reels', likes: 4521, comments: 89 },
  { id: 2, user: 'cooper_retriever', avatar: '🐶', bg: 'linear-gradient(180deg, #56ccf2 0%, #2f80ed 100%)', img: 'https://picsum.photos/seed/lumi30/800/800', caption: 'Wenn der Ball unter dem Sofa liegt... Mission impossible! 🐶 #sofa #dogs', likes: 1830, comments: 41 },
  { id: 3, user: 'berlin_coder', avatar: '💻', bg: 'linear-gradient(180deg, #11998e 0%, #38ef7d 100%)', img: 'https://picsum.photos/seed/lumi31/800/800', caption: 'Wer kennt\'s? "Es läuft auf meinem Rechner..." 🤷‍♂️💻 #devhumor #programming', likes: 962, comments: 23 },
  { id: 4, user: 'potsdam_explorer', avatar: '🗺️', bg: 'linear-gradient(180deg, #833ab4 0%, #fd1d1d 100%)', img: 'https://picsum.photos/seed/lumi32/800/800', caption: 'Der schönste Sonnenuntergang in Potsdam. Wer kennt diese Stelle? 🌅✨ #potsdamliebe #heimat', likes: 3201, comments: 102 },
  { id: 5, user: 'daniel_seidt', avatar: '🐱', bg: 'linear-gradient(180deg, #8e2de2 0%, #4a00e0 100%)', img: 'https://picsum.photos/seed/lumi33/800/800', caption: 'Aspirin auf der internationalen Katzenausstellung am Luftschiffhafen 🏆 #bkh #luftschiffhafen', likes: 6210, comments: 184 },
  { id: 6, user: 'daniel_seidt', avatar: '🐱', bg: 'linear-gradient(180deg, #00b4db 0%, #0083b0 100%)', img: 'https://picsum.photos/seed/lumi34/800/800', caption: 'Segeln auf der Havel, POV vom Bug. Frischer Wind, gute Stimmung ⛵🌬️ #potsdameryachtclub', likes: 2104, comments: 67 },
  { id: 7, user: 'daniel_seidt', avatar: '🐱', bg: 'linear-gradient(180deg, #2c3e50 0%, #4ca1af 100%)', img: 'https://picsum.photos/seed/lumi35/800/800', caption: 'Applaus nach dem 5. Satz im Nikolaisaal. Standing Ovations 🎻👏 #nikolaisaal', likes: 1432, comments: 38 },
  { id: 8, user: 'daniel_seidt', avatar: '🐱', bg: 'linear-gradient(180deg, #56ab2f 0%, #a8e063 100%)', img: 'https://picsum.photos/seed/lumi36/800/800', caption: '10 km an der Panke. Pace stabil, Kopf frei. 🏃‍♂️🌳 #panke #joggen', likes: 987, comments: 21 },
];

export const SUGGESTED_TAGS = [
  '#potsdam', '#nikolaisaal', '#berlinerphilharmoniker',
  '#bkh', '#katzenausstellung', '#luftschiffhafen',
  '#panke', '#parkbabelsberg', '#potsdameryachtclub',
  '#meierei', '#1DEKZV', '#vonderSchönhauser',
  '#segeln', '#brandenburg', '#berlin', '#nature'
];

export const SUGGESTED_PEOPLE = [
  { name: 'cooper_retriever', avatar: '🐶', img: 'https://cdn.hackclub.com/019f52cf-56a1-785d-bed3-7ece540c0579/codebrecher-db8cd6cf.webp', followers: '12,4k' },
  { name: 'berlin_coder', avatar: '💻', img: 'https://cdn.hackclub.com/019f52cf-62a4-7231-9957-0708c2526795/codebrecher-e0501b7b.webp', followers: '8,1k' },
  { name: 'brandenburg_nature', avatar: '🌲', img: 'https://cdn.hackclub.com/019f52cf-5874-7fb3-93f2-6e8e05b39762/pixelfuechse-bd883092.webp', followers: '23k' },
  { name: 'potsdam_explorer', avatar: '🗺️', img: 'https://cdn.hackclub.com/019f52cf-5a36-7b28-8c4a-8dc7ae2dd929/pixelfuechse-e9994f2e.webp', followers: '5,7k' },
  { name: 'helena_seidt', avatar: '👩‍⚖️', img: 'https://picsum.photos/seed/lumi37/800/800', followers: '892' },
  { name: 'dr_henkel', avatar: '🩺', img: 'https://picsum.photos/seed/lumi38/800/800', followers: '1,2k' },
  { name: 'potsdamer_yc', avatar: '⛵', img: 'https://cdn.hackclub.com/019f52cf-4f80-7e8f-9015-c11fc9037df1/codebrecher-c1e086df.webp', followers: '3,2k' },
  { name: 'nikolaisaal', avatar: '🎻', img: 'https://cdn.hackclub.com/019f52cf-517d-7771-8d03-8f5885f37fa7/codebrecher-c589e65c.webp', followers: '8,4k' },
  { name: '1dekv_ev', avatar: '🐾', img: 'https://cdn.hackclub.com/019f52cf-60b1-7c5c-9f32-59dcb51e8a09/codebrecher-cc0a2394.webp', followers: '12k' },
];

export const PROFILE = {
  username: 'daniel_seidt',
  displayName: 'Daniel M. Seidt',
  bio: 'Berlin-Pankow · Wochenende Potsdam 🌳\nVater · Beamtendienst in Berlin 🏛️\nAspirin & Linie 7 (BKH) 🐱 · Joggen an der Panke 🏃\nSegeln im PYC ⛵ · Philharmoniker 🎻 · Nikolaisaal-Pate 🎶\nStaatsrecht & Kortner 📚',
  posts: 142,
  followers: 487,
  following: 312,
  website: 'potsdamer-yacht-club.de',
  avatarImg: 'https://cdn.hackclub.com/019f52cf-4135-766e-9b1f-9a35103a8644/codebrecher-6a9c130c.webp',
};

export const PROFILE_POSTS = [
  { id: 101, user: 'daniel_seidt', bg: 'linear-gradient(45deg, #2c5e2e, #d4af37)', icon: '🌳', img: 'https://cdn.hackclub.com/019f52cf-4dc7-7e24-8d22-1fc08eb63f13/codebrecher-bffb3450.webp' },
  { id: 102, user: 'daniel_seidt', bg: 'linear-gradient(45deg, #f09433, #bc1888)', icon: '🐱' },
  { id: 103, user: 'daniel_seidt', bg: 'linear-gradient(45deg, #c471f5, #fa71cd)', icon: '😻' },
  { id: 104, user: 'daniel_seidt', bg: 'linear-gradient(45deg, #00b4db, #0083b0', icon: '⛵' },
  { id: 105, user: 'daniel_seidt', bg: 'linear-gradient(45deg, #2c3e50, #4ca1af)', icon: '🎻' },
  { id: 106, user: 'daniel_seidt', bg: 'linear-gradient(45deg, #56ab2f, #a8e063)', icon: '🏃' },
  { id: 107, user: 'daniel_seidt', bg: 'linear-gradient(45deg, #00b8a9, #4ecdc4)', icon: '🏊' },
  { id: 108, user: 'daniel_seidt', bg: 'linear-gradient(45deg, #5d4157, #a8caba)', icon: '📚' },
  { id: 109, user: 'daniel_seidt', bg: 'linear-gradient(45deg, #ee9ca7, #ffdde1)', icon: '👨‍👧‍👦' },
  { id: 110, user: 'daniel_seidt', bg: 'linear-gradient(45deg, #f5d7a1, #2c80b8)', icon: '🏖️' },
  { id: 111, user: 'daniel_seidt', bg: 'linear-gradient(45deg, #6a4c93, #c9b1d8)', icon: '🎶' },
  { id: 112, user: 'daniel_seidt', bg: 'linear-gradient(45deg, #8e2de2, #4a00e0)', icon: '🏆' },
];

export const PROFILE_REELS = [
  { id: 1, bg: 'linear-gradient(180deg, #00b4db 0%, #0083b0 100%)' },
  { id: 2, bg: 'linear-gradient(180deg, #2c3e50 0%, #4ca1af 100%)' },
  { id: 3, bg: 'linear-gradient(180deg, #56ab2f 0%, #a8e063 100%)' },
  { id: 4, bg: 'linear-gradient(180deg, #f09433 0%, #bc1888 100%)' },
  { id: 5, bg: 'linear-gradient(180deg, #f5d7a1 0%, #2c80b8 100%)' },
  { id: 6, bg: 'linear-gradient(180deg, #2c5e2e 0%, #d4af37 100%)' },
];

export type StoryItem = {
  id: number;
  user: string;
  avatar: string;
  avatarImg: string | null;
  isOwn: boolean;
  img: string | null;
  time: string;
};

export const STORIES: StoryItem[] = [
  { id: 1, user: 'daniel_seidt', avatar: '🐱', avatarImg: 'https://cdn.hackclub.com/019f52cf-4135-766e-9b1f-9a35103a8644/codebrecher-6a9c130c.webp', isOwn: true, img: 'https://cdn.hackclub.com/019f52cf-4be4-749a-9d38-8fbdf9e30c64/codebrecher-b0e7ce7f.webp', time: 'vor 5 min' },
  { id: 2, user: 'cooper_retriever', avatar: '🐶', avatarImg: 'https://picsum.photos/seed/lumi39/800/800', isOwn: false, img: null, time: '' },
  { id: 3, user: 'berlin_coder', avatar: '💻', avatarImg: 'https://picsum.photos/seed/lumi40/800/800', isOwn: false, img: null, time: '' },
  { id: 4, user: 'potsdam_explorer', avatar: '🗺️', avatarImg: 'https://picsum.photos/seed/lumi41/800/800', isOwn: false, img: null, time: '' },
  { id: 5, user: 'helena_seidt', avatar: '👩‍⚖️', avatarImg: 'https://picsum.photos/seed/lumi42/800/800', isOwn: false, img: null, time: '' },
  { id: 6, user: 'dr_henkel', avatar: '🩺', avatarImg: 'https://picsum.photos/seed/lumi43/800/800', isOwn: false, img: null, time: '' },
  { id: 7, user: '1dekv_ev', avatar: '🐾', avatarImg: 'https://picsum.photos/seed/lumi44/800/800', isOwn: false, img: null, time: '' },
  { id: 201, user: 'markus_seidt', avatar: '⛵', avatarImg: 'https://picsum.photos/seed/lumi45/800/800', isOwn: false, img: null, time: '' },
  { id: 202, user: 'max_reusser', avatar: '🏃', avatarImg: 'https://picsum.photos/seed/lumi46/800/800', isOwn: false, img: null, time: '' },
  { id: 203, user: 'sarah_seidt', avatar: '🎖️', avatarImg: 'https://picsum.photos/seed/lumi47/800/800', isOwn: false, img: null, time: '' },
  { id: 204, user: 'laura_seidt', avatar: '📚', avatarImg: 'https://picsum.photos/seed/lumi48/800/800', isOwn: false, img: null, time: '' },
  { id: 205, user: 'nick_seidt', avatar: '⚽', avatarImg: 'https://picsum.photos/seed/lumi49/800/800', isOwn: false, img: null, time: '' },
  { id: 206, user: 'tobias_brauer', avatar: '⚖️', avatarImg: 'https://picsum.photos/seed/lumi50/800/800', isOwn: false, img: null, time: '' },
  { id: 207, user: 'bernhard_kroll', avatar: '🎖️', avatarImg: 'https://picsum.photos/seed/lumi51/800/800', isOwn: false, img: null, time: '' },
  { id: 208, user: 'sabine_wernecke', avatar: '🏛️', avatarImg: 'https://picsum.photos/seed/lumi52/800/800', isOwn: false, img: null, time: '' },
  { id: 209, user: 'prof_merker', avatar: '🎓', avatarImg: 'https://picsum.photos/seed/lumi53/800/800', isOwn: false, img: null, time: '' },
  { id: 210, user: 'aspirin_vds', avatar: '🐈', avatarImg: 'https://picsum.photos/seed/lumi54/800/800', isOwn: false, img: null, time: '' },
  { id: 301, user: 'potsdam_dogs', avatar: '🐾', avatarImg: 'https://picsum.photos/seed/lumi55/800/800', isOwn: false, img: null, time: '' },
  { id: 302, user: 'dogsof_berlin', avatar: '🔍', avatarImg: 'https://picsum.photos/seed/lumi56/800/800', isOwn: false, img: null, time: '' },
  { id: 303, user: 'outdoor_adventure', avatar: '🕵️', avatarImg: 'https://picsum.photos/seed/lumi57/800/800', isOwn: false, img: null, time: '' },
  { id: 304, user: 'potsdam_culture', avatar: '🧩', avatarImg: 'https://picsum.photos/seed/lumi58/800/800', isOwn: false, img: null, time: '' },
];
